/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Create a new Router instance
 *
 * # Returns
 * JSON object representing the router instance
 */
export declare function createRouter(): string
/**
 * Register a new service
 *
 * # Arguments
 * * `service_json` - JSON string containing service data
 *
 * # Returns
 * JSON object with service details
 */
export declare function registerService(serviceJson: string): string
/**
 * Deregister a service
 *
 * # Arguments
 * * `service_id` - Service ID to deregister
 *
 * # Returns
 * JSON object with operation result
 */
export declare function deregisterService(serviceId: string): string
/**
 * Add a route
 *
 * # Arguments
 * * `route_json` - JSON string containing route data
 *
 * # Returns
 * JSON object with route details
 */
export declare function addRoute(routeJson: string): string
/**
 * Remove a route
 *
 * # Arguments
 * * `route_id` - Route ID to remove
 *
 * # Returns
 * JSON object with operation result
 */
export declare function removeRoute(routeId: string): string
/**
 * Match a request path to a route
 *
 * # Arguments
 * * `path` - Request path to match
 * * `routes_json` - JSON array of routes
 *
 * # Returns
 * JSON object with matched route info or null
 */
export declare function matchRoute(path: string, routesJson: string): string
/**
 * Select a service using round-robin load balancing
 *
 * # Arguments
 * * `route_id` - Route ID
 * * `services_json` - JSON array of services
 *
 * # Returns
 * JSON object with selected service
 */
export declare function selectServiceRoundRobin(routeId: string, servicesJson: string): string
/**
 * Select a service using least connections load balancing
 *
 * # Arguments
 * * `services_json` - JSON array of services
 * * `connections_json` - JSON object with connection counts
 *
 * # Returns
 * JSON object with selected service
 */
export declare function selectServiceLeastConnections(servicesJson: string, connectionsJson: string): string
/**
 * Select a service using weighted load balancing
 *
 * # Arguments
 * * `services_json` - JSON array of services with weights
 *
 * # Returns
 * JSON object with selected service
 */
export declare function selectServiceWeighted(servicesJson: string): string
/**
 * Perform a health check on a service
 *
 * # Arguments
 * * `service_id` - Service ID to check
 * * `host` - Service host
 * * `port` - Service port
 *
 * # Returns
 * JSON object with health check result
 */
export declare function healthCheck(serviceId: string, host: string, port: number): string
/**
 * Batch health checks for multiple services
 *
 * # Arguments
 * * `services_json` - JSON array of services
 *
 * # Returns
 * JSON array with health check results for each service
 */
export declare function batchHealthCheck(servicesJson: string): string
/**
 * Get statistics for a service
 *
 * # Arguments
 * * `_service_id` - Service ID
 * * `stats_json` - JSON object with current stats
 *
 * # Returns
 * JSON object with updated service stats
 */
export declare function getServiceStats(serviceId: string, statsJson: string): string
/**
 * Increment connection counter for a service
 *
 * # Arguments
 * * `_service_id` - Service ID
 *
 * # Returns
 * Updated connection count
 */
export declare function incrementConnections(serviceId: string): number
/**
 * Decrement connection counter for a service
 *
 * # Arguments
 * * `_service_id` - Service ID
 *
 * # Returns
 * Updated connection count
 */
export declare function decrementConnections(serviceId: string): number
/**
 * Get all routes
 *
 * # Arguments
 * * `routes_json` - JSON array of all routes
 *
 * # Returns
 * JSON array with route details
 */
export declare function listRoutes(routesJson: string): string
/**
 * Get all services
 *
 * # Arguments
 * * `services_json` - JSON array of all services
 *
 * # Returns
 * JSON array with service details
 */
export declare function listServices(servicesJson: string): string
