/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Initialize a new trainer with configuration
 *
 * # Arguments
 * * `config_json` - JSON string containing training configuration
 *
 * # Returns
 * Trainer instance ID as a string
 */
export declare function initializeTrainer(configJson: string): string
/**
 * Train a model with the given configuration
 *
 * # Arguments
 * * `trainer_id` - Trainer instance ID
 * * `training_data_json` - JSON string containing training data
 *
 * # Returns
 * Training result with metrics
 */
export declare function trainModel(trainerId: string, trainingDataJson: string): string
/**
 * Evaluate model performance on validation set
 *
 * # Arguments
 * * `_model_id` - Model instance ID
 * * `validation_data_json` - JSON string containing validation data
 *
 * # Returns
 * Evaluation metrics
 */
export declare function evaluateModel(modelId: string, validationDataJson: string): string
/**
 * Run hyperparameter tuning with grid search
 *
 * # Arguments
 * * `hyperparams_json` - JSON string containing hyperparameter definitions
 * * `num_trials` - Number of trials to run
 *
 * # Returns
 * Best hyperparameters and score
 */
export declare function hyperparameterTuning(hyperparamsJson: string, numTrials: number): string
/**
 * Perform optimization on existing model with new hyperparameters
 *
 * # Arguments
 * * `_model_id` - Model instance ID
 * * `hyperparams_json` - JSON string containing new hyperparameters
 *
 * # Returns
 * Optimized model metrics
 */
export declare function optimizeModel(modelId: string, hyperparamsJson: string): string
/**
 * Get training history for a model
 *
 * # Arguments
 * * `_model_id` - Model instance ID
 *
 * # Returns
 * JSON string with training history
 */
export declare function getTrainingHistory(modelId: string): string
/**
 * Batch evaluate multiple models
 *
 * # Arguments
 * * `models_json` - JSON array of model IDs
 * * `validation_data_json` - JSON string containing validation data
 *
 * # Returns
 * Array of evaluation results
 */
export declare function batchEvaluateModels(modelsJson: string, validationDataJson: string): string
/**
 * Validate trainer configuration
 *
 * # Arguments
 * * `config_json` - JSON string containing training configuration
 *
 * # Returns
 * Validation result as JSON
 */
export declare function validateTrainingConfig(configJson: string): string
/**
 * Get optimization suggestions for a model
 *
 * # Arguments
 * * `model_id` - Model instance ID
 * * `metrics_json` - JSON string containing current metrics
 *
 * # Returns
 * JSON string with optimization suggestions
 */
export declare function getOptimizationSuggestions(modelId: string, metricsJson: string): string
