/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Create a new memory manager */
export declare function createMemoryManager(configJson?: string | undefined | null): MemoryManager
/** Get current timestamp (utility function) */
export declare function getTimestamp(): number
/** MemoryManager - Main struct for managing agent memory */
export declare class MemoryManager {
  /** Create a new MemoryManager instance */
  constructor(configJson?: string | undefined | null)
  /** Add to short-term memory */
  addShortTerm(id: string, contentJson: string, priority: number): string
  /** Retrieve from short-term memory */
  getShortTerm(id: string): string | null
  /** Get all short-term memory entries */
  getAllShortTerm(): string
  /** Clear short-term memory */
  clearShortTerm(): number
  /** Add to long-term memory */
  addLongTerm(key: string, contentJson: string): string
  /** Retrieve from long-term memory */
  getLongTerm(key: string): string | null
  /** Get all long-term memory entries */
  getAllLongTerm(): string
  /** Delete from long-term memory */
  deleteLongTerm(key: string): boolean
  /** Clear all long-term memory */
  clearLongTerm(): number
  /** Add to cache with optional TTL */
  cacheSet(key: string, valueJson: string, ttlMs: number): string
  /** Get from cache */
  cacheGet(key: string): string | null
  /** Delete from cache */
  cacheDelete(key: string): boolean
  /** Clear all cache */
  cacheClear(): number
  /** Get cache statistics */
  cacheStats(): string
  /** Allocate memory pool */
  allocatePool(poolId: string, sizeBytes: number): string
  /** Deallocate memory pool */
  deallocatePool(poolId: string): boolean
  /** Get pool status */
  getPoolStatus(poolId: string): string | null
  /** Get all pool statuses */
  getAllPoolStatuses(): string
  /** Get overall memory statistics */
  getMemoryStats(): string
  /** Save state to persistent storage (returns JSON) */
  persistState(): string
  /** Restore state from persistent storage */
  restoreState(stateJson: string): string
}
