/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

const {
  Goalie: NativeGoalie,
  validateInput: nativeValidateInput,
  getVersion: nativeGetVersion,
  benchmark: nativeBenchmark,
} = require('../index.js')

export interface Config {
  /**
   * Operation timeout in milliseconds (default: 5000)
   */
  timeout?: number
  /**
   * Number of retries for failed operations (default: 3)
   */
  retries?: number
  /**
   * Logging level (default: 'info')
   */
  logLevel?: 'debug' | 'info' | 'warn' | 'error'
  /**
   * Maximum concurrent operations (default: 10)
   */
  maxConcurrency?: number
}

export interface ProcessResult {
  /**
   * Whether the operation was successful
   */
  success: boolean
  /**
   * The processed data
   */
  data: Buffer
  /**
   * Human-readable message about the operation
   */
  message: string
}

export class GoalieError extends Error {
  constructor(message: string, public code: string) {
    super(message)
    this.name = 'GoalieError'
  }
}

/**
 * Goalie - AI-powered research assistant
 *
 * @example
 * ```typescript
 * const client = new Goalie()
 * const result = await client.execute()
 * console.log(result)
 * ```
 */
export class Goalie {
  private inner: any

  /**
   * Create a new Goalie client instance
   * @param config - Optional configuration object
   */
  constructor(config?: Config) {
    try {
      this.inner = new NativeGoalie(config)
    } catch (error) {
      throw new GoalieError(
        `Failed to create Goalie client: ${error instanceof Error ? error.message : String(error)}`,
        'INIT_ERROR'
      )
    }
  }

  /**
   * Process input data asynchronously
   *
   * @example
   * ```typescript
   * const input = Buffer.from('Hello, World!')
   * const output = await client.process(input)
   * ```
   *
   * @param data - Input buffer to process
   * @returns Promise resolving to processed buffer
   */
  async process(data: Buffer): Promise<Buffer> {
    try {
      // Wrap sync call in a promise to allow async handling
      return await Promise.resolve(this.inner.processSync(data))
    } catch (error) {
      throw new GoalieError(
        `Process error: ${error instanceof Error ? error.message : String(error)}`,
        'PROCESS_ERROR'
      )
    }
  }

  /**
   * Process input data synchronously
   *
   * @example
   * ```typescript
   * const input = Buffer.from('Hello, World!')
   * const output = client.processSync(input)
   * ```
   *
   * @param data - Input buffer to process
   * @returns Processed buffer
   */
  processSync(data: Buffer): Buffer {
    try {
      return this.inner.processSync(data)
    } catch (error) {
      throw new GoalieError(
        `Sync process error: ${error instanceof Error ? error.message : String(error)}`,
        'PROCESS_SYNC_ERROR'
      )
    }
  }

  /**
   * Execute an operation with optional input
   *
   * @example
   * ```typescript
   * const result = await client.execute(Buffer.from('data'))
   * console.log(result)
   * ```
   *
   * @param input - Optional input buffer
   * @returns Promise resolving to ProcessResult with data and metadata
   */
  async execute(input?: Buffer): Promise<ProcessResult> {
    try {
      // Wrap sync call in a promise to allow async handling
      return await Promise.resolve(this.inner.executeSync(input))
    } catch (error) {
      throw new GoalieError(
        `Execution error: ${error instanceof Error ? error.message : String(error)}`,
        'EXECUTION_ERROR'
      )
    }
  }

  /**
   * Check if the client is still active
   *
   * @returns true if client is active
   */
  isActive(): boolean {
    try {
      return this.inner.isActive()
    } catch (error) {
      return false
    }
  }

  /**
   * Get current client configuration
   *
   * @returns Current configuration object
   */
  getConfig(): Config {
    try {
      return this.inner.getConfig()
    } catch (error) {
      throw new GoalieError(
        `Failed to get config: ${error instanceof Error ? error.message : String(error)}`,
        'CONFIG_ERROR'
      )
    }
  }

  /**
   * Get number of active tasks
   *
   * @returns Number of currently active processing tasks
   */
  getActiveTasks(): number {
    try {
      return this.inner.getActiveTasks()
    } catch (error) {
      throw new GoalieError(
        `Failed to get active tasks: ${error instanceof Error ? error.message : String(error)}`,
        'STATE_ERROR'
      )
    }
  }

  /**
   * Close the client and release resources
   *
   * @example
   * ```typescript
   * await client.close()
   * ```
   *
   * @returns Promise that resolves when cleanup is complete
   */
  async close(): Promise<void> {
    try {
      // Wrap sync call in a promise to allow async handling
      await Promise.resolve(this.inner.closeSync())
    } catch (error) {
      throw new GoalieError(
        `Close error: ${error instanceof Error ? error.message : String(error)}`,
        'CLOSE_ERROR'
      )
    }
  }
}

/**
 * Validate if input buffer is valid
 *
 * @param data - Input buffer to validate
 * @returns true if input is valid
 */
export function validateInput(data: Buffer): boolean {
  try {
    return nativeValidateInput(data)
  } catch (error) {
    return false
  }
}

/**
 * Get the current version of the package
 *
 * @returns Version string
 */
export function getVersion(): string {
  try {
    return nativeGetVersion()
  } catch (error) {
    return '1.0.3'
  }
}

/**
 * Run a benchmark test
 *
 * @param size - Size of data to process in bytes
 * @param iterations - Number of iterations to run
 * @returns Average time per iteration in seconds
 */
export async function benchmarkPerformance(
  size: number,
  iterations: number
): Promise<number> {
  try {
    return await Promise.resolve(nativeBenchmark(size, iterations))
  } catch (error) {
    throw new GoalieError(
      `Benchmark error: ${error instanceof Error ? error.message : String(error)}`,
      'BENCHMARK_ERROR'
    )
  }
}

// Export the class as default for convenience
export default Goalie
