/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Initialize database connection
 *
 * # Arguments
 * * `connection_string` - Connection string for database
 *
 * # Returns
 * AgentDbClient instance
 */
export declare function createClient(connectionString: string): AgentDbClient
/**
 * Check if database client is connected
 *
 * # Arguments
 * * `client_json` - JSON string of client state
 *
 * # Returns
 * Boolean indicating connection status
 */
export declare function isConnected(clientJson: string): boolean
/**
 * Get connection information
 *
 * # Arguments
 * * `connection_string` - Connection string
 *
 * # Returns
 * JSON string with connection info
 */
export declare function getConnectionInfo(connectionString: string): string
/**
 * Create a new agent record in the database
 *
 * # Arguments
 * * `record_json` - JSON string containing agent record
 *
 * # Returns
 * JSON string with created record
 */
export declare function createRecord(recordJson: string): string
/**
 * Read an agent record from the database
 *
 * # Arguments
 * * `record_id` - ID of the record to read
 *
 * # Returns
 * JSON string with agent record
 */
export declare function readRecord(recordId: string): string
/**
 * Update an existing agent record
 *
 * # Arguments
 * * `record_json` - JSON string containing updated record
 *
 * # Returns
 * JSON string with updated record
 */
export declare function updateRecord(recordJson: string): string
/**
 * Delete an agent record from the database
 *
 * # Arguments
 * * `record_id` - ID of the record to delete
 *
 * # Returns
 * JSON object with deletion result
 */
export declare function deleteRecord(recordId: string): string
/**
 * Query records with filtering and pagination
 *
 * # Arguments
 * * `filters_json` - JSON array of query filters
 * * `options_json` - JSON object with query options (offset, limit, sorting)
 *
 * # Returns
 * JSON object with query results
 */
export declare function queryRecords(filtersJson: string, optionsJson: string): string
/**
 * Query records by agent ID
 *
 * # Arguments
 * * `agent_id` - Agent ID to query
 * * `limit` - Maximum records to return
 *
 * # Returns
 * JSON array of agent records
 */
export declare function queryByAgentId(agentId: string, limit: number): string
/**
 * Count records matching filters
 *
 * # Arguments
 * * `filters_json` - JSON array of query filters
 *
 * # Returns
 * Count of matching records
 */
export declare function countRecords(filtersJson: string): number
/**
 * Begin a new transaction
 *
 * # Arguments
 * None
 *
 * # Returns
 * JSON object with transaction ID
 */
export declare function beginTransaction(): string
/**
 * Commit a transaction
 *
 * # Arguments
 * * `transaction_id` - ID of transaction to commit
 *
 * # Returns
 * JSON object with commit result
 */
export declare function commitTransaction(transactionId: string): string
/**
 * Rollback a transaction
 *
 * # Arguments
 * * `transaction_id` - ID of transaction to rollback
 *
 * # Returns
 * JSON object with rollback result
 */
export declare function rollbackTransaction(transactionId: string): string
/**
 * Create multiple records in a batch
 *
 * # Arguments
 * * `records_json` - JSON array of agent records
 *
 * # Returns
 * JSON array with created records
 */
export declare function batchCreateRecords(recordsJson: string): string
/**
 * Update multiple records in a batch
 *
 * # Arguments
 * * `records_json` - JSON array of agent records to update
 *
 * # Returns
 * JSON array with updated records
 */
export declare function batchUpdateRecords(recordsJson: string): string
/**
 * Delete multiple records in a batch
 *
 * # Arguments
 * * `record_ids_json` - JSON array of record IDs to delete
 *
 * # Returns
 * JSON object with deletion results
 */
export declare function batchDeleteRecords(recordIdsJson: string): string
/** In-memory database client for agent persistence */
export declare class AgentDbClient {
  /** Create a new agent database client */
  constructor(connectionString: string)
  /** Check if client is connected */
  isConnected(): boolean
  /** Get connection string */
  getConnectionString(): string
  /** Close the database connection */
  close(): void
}
