/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** FeatureEngine for technical indicators and transformations */
export declare function calculateRsi(pricesJson: string, configJson: string): string
/** Calculate MACD (Moving Average Convergence Divergence) */
export declare function calculateMacd(pricesJson: string, configJson: string): string
/** Calculate Bollinger Bands */
export declare function calculateBollingerBands(pricesJson: string, configJson: string): string
/** Calculate Stochastic Oscillator */
export declare function calculateStochastic(priceDataJson: string, configJson: string): string
/** Calculate Average True Range (ATR) */
export declare function calculateAtr(priceDataJson: string, configJson: string): string
/** Normalize features using various methods */
export declare function normalizeFeatures(featuresJson: string, optionsJson: string): string
/** Calculate rolling window statistics */
export declare function calculateRollingStats(featuresJson: string, windowSize: number): string
/** Calculate feature statistics */
export declare function calculateFeatureStats(featuresJson: string): string
/** Scale features to a specific range */
export declare function scaleFeatures(featuresJson: string, minValue: number, maxValue: number): string
/** Detect outliers using Z-score method */
export declare function detectOutliers(featuresJson: string, threshold: number): string
/** Compute correlation between two feature arrays */
export declare function calculateCorrelation(features1Json: string, features2Json: string): number
