/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Create a new response engine
 *
 * # Returns
 * A new ResponseEngine instance as JSON string
 */
export declare function createResponseEngine(): string
/**
 * Register a policy rule with the engine
 *
 * # Arguments
 * * `rule_json` - JSON string containing the policy rule
 *
 * # Returns
 * JSON string with registration result
 */
export declare function registerPolicyRule(ruleJson: string): string
/**
 * Evaluate policies against an incident
 *
 * # Arguments
 * * `incident_json` - JSON string containing incident data
 * * `policies_json` - JSON string containing policy rules
 *
 * # Returns
 * JSON string with policy evaluation result
 */
export declare function evaluatePolicies(incidentJson: string, policiesJson: string): string
/**
 * Execute response actions for an incident
 *
 * # Arguments
 * * `incident_json` - JSON string containing incident data
 * * `actions_json` - JSON string containing actions to execute
 *
 * # Returns
 * JSON string with execution result
 */
export declare function executeResponseActions(incidentJson: string, actionsJson: string): string
/**
 * Execute enforcement of policy rules
 *
 * # Arguments
 * * `enforcement_json` - JSON string containing enforcement parameters
 *
 * # Returns
 * JSON string with enforcement result
 */
export declare function enforcePolicy(enforcementJson: string): string
/**
 * Rollback executed actions
 *
 * # Arguments
 * * `action_id` - ID of the action to rollback
 * * `context_json` - JSON string with rollback context
 *
 * # Returns
 * JSON string with rollback result
 */
export declare function rollbackAction(actionId: string, contextJson: string): string
/**
 * Get action status
 *
 * # Arguments
 * * `action_id` - ID of the action to check
 *
 * # Returns
 * JSON string with action status information
 */
export declare function getActionStatus(actionId: string): string
/**
 * Batch evaluate multiple incidents
 *
 * # Arguments
 * * `incidents_json` - JSON array of incidents
 * * `policies_json` - JSON array of policies
 *
 * # Returns
 * JSON string with batch evaluation results
 */
export declare function batchEvaluateIncidents(incidentsJson: string, policiesJson: string): string
/**
 * Create automatic incident response workflow
 *
 * # Arguments
 * * `workflow_json` - JSON string with workflow configuration
 *
 * # Returns
 * JSON string with workflow result
 */
export declare function createWorkflow(workflowJson: string): string
/**
 * Generate incident response report
 *
 * # Arguments
 * * `report_json` - JSON string with report parameters
 *
 * # Returns
 * JSON string with comprehensive report
 */
export declare function generateResponseReport(reportJson: string): string
