/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** CLI Runner for executing commands */
export declare class CliRunner {
  /** Create a new CLI Runner instance */
  constructor(config?: object | undefined | null)
  /** Parse and execute a command */
  executeCommand(commandJson: string): string
  /** Initialize a swarm */
  initializeSwarm(swarmId: string, configJson: string): string
  /** Start a swarm */
  startSwarm(swarmId: string): string
  /** Stop a swarm */
  stopSwarm(swarmId: string): string
  /** Get swarm status */
  getSwarmStatus(swarmId: string): string
  /** List all swarms */
  listSwarms(): string
  /** Deploy configuration to swarm */
  deployConfig(swarmId: string, configJson: string): string
  /** Scale swarm to specified agent count */
  scaleSwarm(swarmId: string, agentCount: number): string
  /** Get monitoring data */
  getMonitoringData(): string
  /** Get CLI configuration */
  getConfig(): string
  /** Get command history */
  getHistory(limit: number): string
  /** Clear command history */
  clearHistory(): string
}
