/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Process a single task
 *
 * # Arguments
 * * `task_json` - JSON string containing task data
 *
 * # Returns
 * JSON string with task result
 */
export declare function processTask(taskJson: string): string
/**
 * Schedule multiple tasks and execute them
 *
 * # Arguments
 * * `tasks_json` - JSON array string containing task objects
 *
 * # Returns
 * JSON array string with execution results
 */
export declare function scheduleTasks(tasksJson: string): string
/**
 * Get execution statistics for a batch
 *
 * # Arguments
 * * `tasks_json` - JSON array string containing task objects
 *
 * # Returns
 * JSON string with execution statistics
 */
export declare function getExecutionStats(tasksJson: string): string
/**
 * Create a configuration object
 *
 * # Arguments
 * * `config_json` - JSON string containing configuration options
 *
 * # Returns
 * JSON string with validated configuration
 */
export declare function createConfig(configJson: string): string
/**
 * Calculate the latency of a task
 *
 * # Arguments
 * * `task_json` - JSON string containing task data
 * * `iterations` - Number of iterations to measure
 *
 * # Returns
 * Latency in nanoseconds as a JSON object
 */
export declare function measureLatency(taskJson: string, iterations: number): string
/**
 * Process a task with retry logic
 *
 * # Arguments
 * * `task_json` - JSON string containing task data
 * * `max_retries` - Maximum number of retries
 *
 * # Returns
 * JSON string with task result
 */
export declare function processTaskWithRetries(taskJson: string, maxRetries: number): string
