/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Process Geometric Langlands data
 *
 * # Arguments
 * * `config_json` - JSON string containing configuration
 * * `data_json` - JSON string containing input data
 *
 * # Returns
 * JSON string with computation result
 */
export declare function processGeometricLanglands(configJson: string, dataJson: string): string
/**
 * Compute automorphic forms for Geometric Langlands
 *
 * # Arguments
 * * `dimension` - Dimension of the automorphic form
 * * `num_coefficients` - Number of coefficients to compute
 *
 * # Returns
 * JSON string with automorphic form data
 */
export declare function computeAutomorphicForms(dimension: number, numCoefficients: number): string
/**
 * Apply Hecke operators to automorphic forms
 *
 * # Arguments
 * * `forms_json` - JSON string containing automorphic forms
 * * `operator_name` - Name of the Hecke operator
 *
 * # Returns
 * JSON string with Hecke operator results
 */
export declare function applyHeckeOperators(formsJson: string, operatorName: string): string
/**
 * Compute geometric objects from spectral data
 *
 * # Arguments
 * * `spectral_data_json` - JSON string containing spectral data
 * * `object_type` - Type of geometric object to compute
 *
 * # Returns
 * JSON array string with geometric objects
 */
export declare function computeGeometricObjects(spectralDataJson: string, objectType: string): string
/**
 * Verify Langlands correspondence for given data
 *
 * # Arguments
 * * `data1_json` - First set of data as JSON string
 * * `data2_json` - Second set of data as JSON string
 *
 * # Returns
 * Correspondence score (0.0 to 1.0)
 */
export declare function verifyLanglandsCorrespondence(data1Json: string, data2Json: string): number
/**
 * Batch process multiple Geometric Langlands computations
 *
 * # Arguments
 * * `data_array_json` - JSON array string containing multiple data items
 *
 * # Returns
 * JSON array string with computation results
 */
export declare function batchProcessLanglands(dataArrayJson: string): string
