/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Utility function: Create a simple QUIC stream */
export declare function createSimpleStream(priority: number): string
/** Utility function: Calculate stream efficiency */
export declare function calculateStreamEfficiency(dataSent: number, dataReceived: number, totalTimeMs: number): number
/** QUIC client with multi-stream support */
export declare class QuicClient {
  /** Create a new QUIC client with optional configuration */
  constructor(config?: string | undefined | null)
  /**
   * Create a new stream
   * Returns the stream ID
   */
  createStream(priority: number): number
  /**
   * Send data on a specific stream
   * Returns the number of bytes sent
   */
  sendData(streamId: number, size: number): number
  /**
   * Receive data on a specific stream
   * Returns the number of bytes received
   */
  receiveData(streamId: number, size: number): number
  /**
   * Close a specific stream
   * Returns operation result as JSON
   */
  closeStream(streamId: number): string
  /**
   * Get information about a specific stream
   * Returns stream info as JSON
   */
  getStreamInfo(streamId: number): string
  /**
   * Get all active streams
   * Returns array of stream IDs as JSON
   */
  getActiveStreams(): string
  /**
   * Get statistics about all streams
   * Returns stats as JSON
   */
  getStats(): string
  /**
   * Reset a stream with optional error code
   * Returns operation result as JSON
   */
  resetStream(streamId: number, errorCode: number): string
  /**
   * Close all streams
   * Returns the number of streams closed
   */
  closeAllStreams(): number
  /**
   * Set stream priority
   * Returns operation result as JSON
   */
  setStreamPriority(streamId: number, priority: number): string
}
