/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Hash a key for DHT storage */
export declare function hashKey(key: string): string
/** Validate DHT key format */
export declare function validateKey(key: string): boolean
/** Create a default DHT configuration */
export declare function createDefaultConfig(): string
/** Calculate storage size for an entry */
export declare function calculateEntrySize(key: string, value: string): number
/** Create a DHTEntry object */
export declare function createDhtEntry(key: string, value: string, ttlMs: number): string
/** DHT Node structure - main interface for distributed hash table operations */
export declare class DhtNode {
  /** Create a new DHT Node */
  constructor(configJson?: string | undefined | null)
  /** Store a value in the DHT */
  put(key: string, value: string, ttlMs: number): boolean
  /** Retrieve a value from the DHT */
  get(key: string): string
  /** Delete a value from the DHT */
  delete(key: string): boolean
  /** Check if a key exists in the DHT */
  exists(key: string): boolean
  /** Perform a DHT lookup (simulated Kademlia-style) */
  lookup(key: string, maxHops: number): string
  /** Add a peer node to the routing table */
  addPeer(nodeId: string, distance: number): boolean
  /** Remove a peer from the routing table */
  removePeer(nodeId: string): boolean
  /** Get all peers in routing table */
  getPeers(): string
  /** Get peer count in routing table */
  peerCount(): number
  /** Get all stored entries in local storage */
  getAllEntries(): string
  /** Get entry count in local storage */
  entryCount(): number
  /** Get node ID */
  getNodeId(): string
  /** Get configuration */
  getConfig(): string
  /** Get replication status for a key */
  getReplicationStatus(key: string): string
  /** Perform health check */
  healthCheck(): string
  /** Get DHT statistics */
  getStats(): string
  /** Clear all local storage */
  clear(): boolean
}
