/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Market data point with timestamp and metadata */
export interface MarketDataPoint {
  symbol: string
  price: number
  volume: number
  timestamp: number
  bid: number
  ask: number
  bidSize: number
  askSize: number
}
/** Event type for stream notifications */
export const enum EventType {
  DataReceived = 0,
  ConnectionEstablished = 1,
  ConnectionClosed = 2,
  Error = 3,
  Reconnecting = 4
}
/** Stream event with metadata */
export interface StreamEvent {
  eventType: string
  message: string
  timestamp: number
  streamId: string
}
/** Connection state information */
export interface ConnectionState {
  streamId: string
  isConnected: boolean
  errorCount: number
  dataCount: number
  lastHeartbeat: number
  uptimeMs: number
}
/** Statistics for stream performance */
export interface StreamStatistics {
  streamId: string
  totalMessages: number
  totalErrors: number
  averageLatencyMs: number
  bytesReceived: number
  uptimeSeconds: number
  reconnectCount: number
}
/** Create a new stream manager */
export declare function createStreamManager(url: string, timeoutMs?: number | undefined | null): StreamManager
/** Global event handler registry */
export interface EventHandler {
  eventType: string
  handlerId: string
}
/** Create event listener */
export declare function createEventListener(eventType: string): EventHandler
/** Process market data JSON */
export declare function processMarketData(dataJson: string): string
/** Validate stream configuration */
export declare function validateStreamConfig(configJson: string): boolean
/** Format stream event */
export declare function formatStreamEvent(eventType: string, message: string, streamId: string): string
/** Parse market data from JSON array */
export declare function parseMarketDataBatch(dataJson: string): string
/** StreamManager for handling real-time market data connections */
export declare class StreamManager {
  /** Create a new StreamManager instance */
  constructor(url: string, timeoutMs?: number | undefined | null)
  /** Connect to the WebSocket stream */
  connect(): boolean
  /** Disconnect from the stream */
  disconnect(): boolean
  /** Check if stream is connected */
  isConnected(): boolean
  /** Get the stream ID */
  getStreamId(): string
  /** Add market data to the stream */
  addMarketData(symbol: string, price: number, volume: number): void
  /** Get buffered messages */
  getBufferedMessages(): Array<string>
  /** Clear the message buffer */
  clearBuffer(): void
  /** Get connection state */
  getConnectionState(): ConnectionState
  /** Get stream statistics */
  getStatistics(): StreamStatistics
  /** Reconnect to the stream */
  reconnect(): boolean
  /** Subscribe to a symbol */
  subscribe(symbol: string): void
  /** Unsubscribe from a symbol */
  unsubscribe(symbol: string): void
  /** Send heartbeat ping */
  heartbeat(): void
  /** Get current message buffer size */
  getBufferSize(): number
  /** Reset error count */
  resetErrorCount(): void
  /** Get error count */
  getErrorCount(): number
  /** Get data count */
  getDataCount(): number
  /** Process batch of market data updates */
  batchAddMarketData(dataJson: string): number
  /** Get configuration */
  getConfig(): string
  /** Update configuration */
  updateConfig(configJson: string): void
  /** Get total bytes received */
  getTotalBytes(): number
  /** Get reconnect count */
  getReconnectCount(): number
  /** Reset all statistics */
  resetStatistics(): void
}
