/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Create a new sheaf */
export declare function createSheaf(id: string, baseSpace: string, dimension: number): string
/** Perform cohomology computation on a sheaf */
export declare function computeCohomology(sheafJson: string): string
/** Perform tensor product of two sheaves */
export declare function tensorProductSheaves(sheaf1Json: string, sheaf2Json: string): string
/** Perform restriction of a sheaf */
export declare function restrictSheaf(sheafJson: string, restrictionJson: string): string
/** Format computation result for display */
export declare function formatResultForDisplay(resultJson: string, format: string): string
/** Create visualization metadata */
export declare function createVisualization(visType: string, width: number, height: number, colorScheme: string): string
/** Batch execute multiple computation tasks */
export declare function batchExecuteTasks(tasksJson: string): string
/** Parse and validate Geometric Langlands specification */
export declare function parseLanglandsSpec(specJson: string): string
/** Create a modular form */
export declare function createModularForm(weight: number, level: number, character: string): string
/** Compute Hecke eigenvalues for a modular form */
export declare function computeHeckeEigenvalues(formJson: string, primeCount: number): string
/** Create a Galois representation */
export declare function createGaloisRepresentation(representationType: string, dimension: number, field: string): string
/** Analyze Galois representation irreducibility */
export declare function analyzeRepresentationIrreducibility(repJson: string): string
/** Compare two Galois representations */
export declare function compareGaloisRepresentations(rep1Json: string, rep2Json: string): string
/** Main LanglandsCli class */
export declare class LanglandsCli {
  /** Create new LanglandsCli instance */
  constructor(configJson?: string | undefined | null)
  /** Get CLI configuration */
  getConfig(): string
  /** Create a new computation task */
  createTask(taskType: string, paramsJson: string): string
  /** Execute a computation task */
  executeTask(taskJson: string): string
  /** Compute modular form from parameters */
  computeModularForm(weight: number, level: number, characterJson: string): string
  /** Analyze Galois representation */
  analyzeGaloisRepresentation(repJson: string, analysisType: string): string
}
