/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

const {
  DetectionEngine: DetectionEngineNative,
  patternMatch,
  calculateSeverity,
  generateEventId,
  validateEvent,
} = require('../index')

export interface DetectionSignature {
  signature_id: string
  name: string
  pattern: string
  signature_type: string
  severity: string
  enabled: boolean
}

export interface DetectionEvent {
  event_id: string
  event_type: string
  severity: string
  timestamp: string
  source: string
  destination: string
  payload: string
  metadata: Record<string, any>
}

export interface DetectionResult {
  detected: boolean
  signature_id?: string
  signature_name?: string
  severity: string
  confidence: number
  matched_pattern?: string
  event_details: Record<string, any>
}

export interface AnomalyResult {
  is_anomaly: boolean
  anomaly_type: string
  anomaly_score: number
  threshold_exceeded: boolean
  metrics: Record<string, any>
}

export interface CorrelationResult {
  correlated: boolean
  correlation_type: string
  related_events: string[]
  correlation_score: number
}

export interface ThresholdConfig {
  metric_name: string
  threshold_value: number
  duration_seconds: number
  comparison_operator: string
}

/**
 * DetectionEngine class for real-time AIMDS detection
 *
 * @example
 * ```typescript
 * const engine = new DetectionEngine(5000)
 * engine.registerSignature(JSON.stringify({
 *   signature_id: 'sig_001',
 *   name: 'SQL Injection',
 *   pattern: 'SELECT.*FROM',
 *   signature_type: 'regex',
 *   severity: 'high',
 *   enabled: true
 * }))
 * ```
 */
export class DetectionEngine {
  private inner: any

  /**
   * Create a new DetectionEngine instance
   * @param maxHistorySize - Maximum number of events to keep in history (default: 10000)
   */
  constructor(maxHistorySize?: number) {
    this.inner = new DetectionEngineNative(maxHistorySize)
  }

  /**
   * Register a detection signature
   * @param signatureJson - JSON string containing signature definition
   * @returns True if registration successful
   */
  registerSignature(signatureJson: string): boolean {
    return this.inner.registerSignature(signatureJson)
  }

  /**
   * Register a threshold configuration
   * @param thresholdJson - JSON string containing threshold configuration
   * @returns True if registration successful
   */
  registerThreshold(thresholdJson: string): boolean {
    return this.inner.registerThreshold(thresholdJson)
  }

  /**
   * Match event against all registered signatures
   * @param eventJson - JSON string containing event data
   * @returns Detection result
   */
  matchSignature(eventJson: string): DetectionResult {
    const resultJson = this.inner.matchSignature(eventJson)
    return JSON.parse(resultJson)
  }

  /**
   * Detect intrusion patterns in an event
   * @param eventJson - JSON string containing event data
   * @returns Detection result
   */
  detectIntrusion(eventJson: string): DetectionResult {
    const resultJson = this.inner.detectIntrusion(eventJson)
    return JSON.parse(resultJson)
  }

  /**
   * Detect anomalous behavior
   * @param eventJson - JSON string containing event data
   * @returns Anomaly detection result
   */
  detectAnomaly(eventJson: string): AnomalyResult {
    const resultJson = this.inner.detectAnomaly(eventJson)
    return JSON.parse(resultJson)
  }

  /**
   * Correlate two events for pattern detection
   * @param event1Json - JSON string containing first event
   * @param event2Json - JSON string containing second event
   * @returns Correlation result
   */
  correlateEvents(event1Json: string, event2Json: string): CorrelationResult {
    const resultJson = this.inner.correlateEvents(event1Json, event2Json)
    return JSON.parse(resultJson)
  }

  /**
   * Monitor a metric against its threshold
   * @param metricName - Name of the metric
   * @param metricValue - Current value of the metric
   * @returns True if threshold is exceeded
   */
  monitorThreshold(metricName: string, metricValue: number): boolean {
    return this.inner.monitorThreshold(metricName, metricValue)
  }

  /**
   * Record an event in the engine's history
   * @param eventJson - JSON string containing event data
   * @returns The recorded event
   */
  recordEvent(eventJson: string): DetectionEvent {
    const resultJson = this.inner.recordEvent(eventJson)
    return JSON.parse(resultJson)
  }

  /**
   * Get the size of the event history
   * @returns Number of events in history
   */
  getHistorySize(): number {
    return this.inner.getHistorySize()
  }

  /**
   * Get the count of registered signatures
   * @returns Number of signatures
   */
  getSignatureCount(): number {
    return this.inner.getSignatureCount()
  }

  /**
   * Get the count of registered thresholds
   * @returns Number of thresholds
   */
  getThresholdCount(): number {
    return this.inner.getThresholdCount()
  }

  /**
   * Clear all signatures
   * @returns True if successful
   */
  clearSignatures(): boolean {
    return this.inner.clearSignatures()
  }

  /**
   * Clear all thresholds
   * @returns True if successful
   */
  clearThresholds(): boolean {
    return this.inner.clearThresholds()
  }

  /**
   * Clear event history
   * @returns True if successful
   */
  clearHistory(): boolean {
    return this.inner.clearHistory()
  }
}

/**
 * Check if text matches a regex pattern
 * @param text - Text to check
 * @param pattern - Regex pattern
 * @returns True if pattern matches
 */
export function patternMatchUtil(text: string, pattern: string): boolean {
  return patternMatch(text, pattern)
}

/**
 * Calculate severity score from indicators
 * @param indicators - Array of severity indicators
 * @returns Severity score (0.0 - 1.0)
 */
export function calculateSeverityScore(indicators: string[]): number {
  return calculateSeverity(indicators)
}

/**
 * Generate a unique event ID
 * @param prefix - Prefix for the event ID
 * @returns Generated event ID
 */
export function generateId(prefix: string): string {
  return generateEventId(prefix)
}

/**
 * Validate event structure
 * @param eventJson - JSON string containing event data
 * @returns True if event is valid
 */
export function isValidEvent(eventJson: string): boolean {
  return validateEvent(eventJson)
}

// Export the class as default for convenience
export default DetectionEngine
