/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Process input data with evolutionary neural network encoding
 *
 * # Arguments
 * * `input_json` - JSON string containing input data
 *
 * # Returns
 * JSON string with processed result
 */
export declare function processData(inputJson: string): string
/**
 * Process data with genetic encoding optimization
 *
 * # Arguments
 * * `input_json` - JSON string containing input data
 * * `encoding_type` - Type of genetic encoding to use
 *
 * # Returns
 * JSON string with encoded result
 */
export declare function encodeData(inputJson: string, encodingType: string): string
/**
 * Evaluate a neural network with input data
 *
 * # Arguments
 * * `network_json` - JSON string containing neural network configuration
 * * `input_json` - JSON string containing input data
 *
 * # Returns
 * JSON string with evaluation result
 */
export declare function evaluateNetwork(networkJson: string, inputJson: string): string
/**
 * Batch process multiple inputs
 *
 * # Arguments
 * * `batch_json` - JSON array string with multiple inputs
 *
 * # Returns
 * JSON array string with results
 */
export declare function batchProcess(batchJson: string): string
/**
 * Get evolutionary network statistics
 *
 * # Arguments
 * * `data_json` - JSON string containing data
 *
 * # Returns
 * JSON string with statistics
 */
export declare function getStatistics(dataJson: string): string
