/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Calculate Finite-Time Lyapunov Exponent (FTLE) for a point
 *
 * # Arguments
 * * `point_json` - JSON representation of trajectory point
 * * `config_json` - JSON configuration for FTLE calculation
 *
 * # Returns
 * JSON string with FTLE result
 */
export declare function calculateFtle(pointJson: string, configJson: string): string
/**
 * Analyze attractor dynamics for a trajectory
 *
 * # Arguments
 * * `trajectory_json` - JSON array of trajectory points
 * * `_config_json` - JSON configuration
 *
 * # Returns
 * JSON string with attractor analysis
 */
export declare function analyzeAttractor(trajectoryJson: string, configJson: string): string
/**
 * Analyze temporal dynamics of a trajectory
 *
 * # Arguments
 * * `trajectory_json` - JSON array of trajectory points
 *
 * # Returns
 * JSON string with temporal dynamics analysis
 */
export declare function analyzeTemporalDynamics(trajectoryJson: string): string
/**
 * Predict future trajectory points based on attractor dynamics
 *
 * # Arguments
 * * `trajectory_json` - JSON array of past trajectory points
 * * `steps` - Number of steps to predict
 *
 * # Returns
 * JSON array of predicted trajectory points
 */
export declare function predictTrajectory(trajectoryJson: string, steps: number): string
/**
 * Calculate VP-tree based nearest neighbors with VP-tree optimization
 *
 * # Arguments
 * * `points_json` - JSON array of points
 * * `query_point_json` - Query point as JSON
 * * `k` - Number of nearest neighbors
 *
 * # Returns
 * JSON array of k nearest neighbors
 */
export declare function findNearestNeighbors(pointsJson: string, queryPointJson: string, k: number): string
