/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

const {
  AimdsCoreClient,
  createClient: nativeCreateClient,
  processBuffer: nativeProcessBuffer,
  version: nativeVersion,
} = require('../index')

/**
 * Configuration options for AIMDS Core
 */
export interface Config {
  timeout?: number
  retries?: number
  logLevel?: string
  maxConcurrency?: number
}

/**
 * Result object from processing operations
 */
export interface ProcessResult {
  success: boolean
  data: Buffer
  message?: string
}

/**
 * AIMDS Core Client for processing data with native performance
 *
 * @example
 * ```typescript
 * const client = new AimdsCore({
 *   timeout: 5000,
 *   retries: 3
 * })
 *
 * const input = Buffer.from('sample data')
 * const result = await client.process(input)
 * console.log(result)
 *
 * await client.close()
 * ```
 */
export class AimdsCore {
  private inner: any

  /**
   * Create a new AIMDS Core client
   * @param config - Optional configuration options
   */
  constructor(config?: Config) {
    const convertedConfig = config ? convertConfig(config) : undefined
    this.inner = new AimdsCoreClient(convertedConfig)
  }

  /**
   * Process input data synchronously
   * @param data - Input buffer to process
   * @returns Process result containing success status and data
   * @throws Error if client is not ready or data is invalid
   */
  processSync(data: Buffer): ProcessResult {
    const result = this.inner.processSync(data)
    return {
      success: result.success,
      data: Buffer.from(result.data),
      message: result.message,
    }
  }

  /**
   * Process input data asynchronously
   * @param data - Input buffer to process
   * @returns Promise that resolves to process result
   * @throws Error if client is not ready or data is invalid
   */
  async process(data: Buffer): Promise<ProcessResult> {
    const result = await this.inner.process(data)
    return {
      success: result.success,
      data: Buffer.from(result.data),
      message: result.message,
    }
  }

  /**
   * Check if the client is ready and operational
   * @returns True if client is operational, false otherwise
   */
  isReady(): boolean {
    return this.inner.isReady()
  }

  /**
   * Get the current timeout setting
   * @returns Timeout value in milliseconds
   */
  getTimeout(): number {
    return this.inner.getTimeout()
  }

  /**
   * Close the client and release resources
   * @returns Promise that resolves when cleanup is complete
   */
  async close(): Promise<void> {
    await this.inner.close()
  }
}

/**
 * Converts camelCase config to snake_case for Rust
 */
function convertConfig(config: Config): any {
  return {
    timeout: config.timeout,
    retries: config.retries,
    log_level: config.logLevel,
    max_concurrency: config.maxConcurrency,
  }
}

/**
 * Create a new AIMDS Core client with default configuration
 *
 * @example
 * ```typescript
 * const client = createClient()
 * const result = await client.process(Buffer.from('data'))
 * ```
 *
 * @returns A new AimdsCore client instance
 */
export function createClient(): AimdsCore {
  const nativeClient = nativeCreateClient()
  const client = new AimdsCore()
  client['inner'] = nativeClient
  return client
}

/**
 * Process a buffer with a default client (utility function)
 *
 * @example
 * ```typescript
 * const result = processBuffer(Buffer.from('data'))
 * console.log(result.success) // true
 * ```
 *
 * @param data - Input buffer to process
 * @returns Process result containing success status and data
 */
export function processBuffer(data: Buffer): ProcessResult {
  const result = nativeProcessBuffer(data)
  return {
    success: result.success,
    data: Buffer.from(result.data),
    message: result.message,
  }
}

/**
 * Get version information
 *
 * @example
 * ```typescript
 * console.log(version()) // "aimds-core-napi 0.1.0"
 * ```
 *
 * @returns Version string
 */
export function version(): string {
  return nativeVersion()
}

// Export AimdsCore as default for convenience
export default AimdsCore
