/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Execute order using TWAP algorithm */
export declare function executeTwap(totalQuantity: number, timeWindowMs: number, sliceIntervalMs: number, urgency: number): string
/** Execute order using VWAP algorithm */
export declare function executeVwap(totalQuantity: number, volumeParticipationRate: number, lookbackPeriodMs: number): string
/** Execute market order directly */
export declare function executeMarket(quantity: number, marketConditions: string): string
/** Execute limit order with routing */
export declare function executeLimit(quantity: number, limitPrice: number, timeToExpiryMs: number): string
/** Smart order routing across venues */
export declare function smartOrderRouting(symbol: string, quantity: number, primaryExchange: string, secondaryExchangesJson: string): string
/** Main execution engine managing order lifecycle */
export declare class ExecutionEngine {
  constructor()
  createOrder(symbol: string, side: string, orderType: string, quantity: number, price?: number | undefined | null): string
  submitOrder(orderId: string): string
  recordFill(orderId: string, quantity: number, price: number, exchange: string): string
  getOrder(orderId: string): string
  getOrderFills(orderId: string): string
  cancelOrder(orderId: string): string
  generateExecutionReport(orderId: string): string
  getAllOrders(): string
  getOrderStats(): string
}
