/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Initialize a neural network solver
 *
 * # Arguments
 * * `config_json` - JSON string containing neural network configuration
 *
 * # Returns
 * JSON string with initialization result
 */
export declare function initializeSolver(configJson: string): string
/**
 * Process temporal events through neural network
 *
 * # Arguments
 * * `events_json` - JSON string containing temporal events
 *
 * # Returns
 * JSON string with processed events
 */
export declare function processTemporalEvents(eventsJson: string): string
/**
 * Train neural network on temporal data
 *
 * # Arguments
 * * `training_data_json` - JSON string containing training data
 * * `config_json` - JSON string containing training configuration
 *
 * # Returns
 * JSON string with training results
 */
export declare function trainTemporalModel(trainingDataJson: string, configJson: string): string
/**
 * Make predictions on temporal data
 *
 * # Arguments
 * * `input_json` - JSON string containing input features
 * * `model_json` - JSON string containing model configuration
 *
 * # Returns
 * JSON string with predictions
 */
export declare function predictTemporal(inputJson: string, modelJson: string): string
/**
 * Detect temporal patterns in event sequence
 *
 * # Arguments
 * * `events_json` - JSON string containing temporal events
 * * `pattern_type` - Type of pattern to detect (e.g., "periodic", "trend")
 *
 * # Returns
 * JSON string with detected patterns
 */
export declare function detectTemporalPatterns(eventsJson: string, patternType: string): string
/**
 * Calculate neural network performance metrics
 *
 * # Arguments
 * * `predictions_json` - JSON string containing predictions
 * * `actual_json` - JSON string containing actual values
 *
 * # Returns
 * JSON string with performance metrics
 */
export declare function calculatePerformanceMetrics(predictionsJson: string, actualJson: string): string
/**
 * Batch process multiple temporal sequences
 *
 * # Arguments
 * * `sequences_json` - JSON array string containing temporal event sequences
 *
 * # Returns
 * JSON array string with processed sequences
 */
export declare function batchProcessSequences(sequencesJson: string): string
