/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

const {
  QuDagProtocol,
  createProtocol: nativeCreateProtocol,
  validateMessage: nativeValidateMessage,
  getProtocolVersion: nativeGetProtocolVersion,
  processDataDefault: nativeProcessDataDefault,
} = require('../index')

/**
 * Protocol configuration options
 */
export interface ProtocolConfig {
  timeoutMs?: number
  maxRetries?: number
  enableOptimization?: boolean
  nodeId?: string
}

/**
 * Protocol message structure
 */
export interface ProtocolMessage {
  messageType: string
  sourceNode: string
  destinationNode: string
  payload: Buffer | Uint8Array
  timestamp: number
}

/**
 * Result of protocol operations
 */
export interface OperationResult {
  success: boolean
  message: string
  data: Buffer
  timestamp: number
}

/**
 * QuDAG Protocol Coordinator
 *
 * Main interface for orchestrating crypto, DAG, and network components.
 *
 * @example
 * ```typescript
 * const protocol = new QuDAGProtocol({
 *   nodeId: 'node-1',
 *   timeoutMs: 30000
 * })
 *
 * // Initialize and send message
 * await protocol.initialize()
 * const result = await protocol.sendMessage({
 *   messageType: 'protocol',
 *   sourceNode: 'node-1',
 *   destinationNode: 'node-2',
 *   payload: Buffer.from('hello'),
 *   timestamp: Date.now()
 * })
 * ```
 */
export class QuDAGProtocolClass {
  private inner: any

  /**
   * Create a new QuDAG Protocol coordinator
   * @param config - Protocol configuration options
   */
  constructor(config?: ProtocolConfig) {
    this.inner = new QuDagProtocol(config)
  }

  /**
   * Initialize the protocol
   * @returns true if initialization was successful
   */
  initialize(): boolean {
    return this.inner.initialize()
  }

  /**
   * Send a protocol message
   * @param message - The message to send
   * @returns Operation result
   */
  async sendMessage(message: ProtocolMessage): Promise<OperationResult> {
    const nativeMessage: any = {
      messageType: message.messageType,
      sourceNode: message.sourceNode,
      destinationNode: message.destinationNode,
      payload: Buffer.isBuffer(message.payload)
        ? Array.from(message.payload)
        : Array.from(message.payload as Uint8Array),
      timestamp: message.timestamp,
    }
    const result = await this.inner.sendMessage(nativeMessage)
    return {
      success: result.success,
      message: result.message,
      data: Buffer.from(result.data),
      timestamp: result.timestamp,
    }
  }

  /**
   * Receive a protocol message
   * @param messageData - Raw message data
   * @returns Parsed protocol message
   */
  receiveMessage(messageData: Buffer | Uint8Array): ProtocolMessage {
    const messageArray = Buffer.isBuffer(messageData)
      ? Array.from(messageData)
      : Array.from(messageData as Uint8Array)
    const result = this.inner.receiveMessage(messageArray)
    return {
      messageType: result.messageType,
      sourceNode: result.sourceNode,
      destinationNode: result.destinationNode,
      payload: Buffer.from(result.payload),
      timestamp: result.timestamp,
    }
  }

  /**
   * Process data using the protocol
   * @param data - Data to process
   * @returns Processing result
   */
  async processData(data: Buffer | Uint8Array): Promise<OperationResult> {
    const buffer = Buffer.isBuffer(data) ? data : Buffer.from(data)
    const result = await this.inner.processData(buffer)
    return {
      success: result.success,
      message: result.message,
      data: Buffer.from(result.data),
      timestamp: result.timestamp,
    }
  }

  /**
   * Validate protocol state
   * @returns true if protocol state is valid
   */
  validateState(): boolean {
    return this.inner.validateState()
  }

  /**
   * Get current timeout configuration
   * @returns Timeout in milliseconds
   */
  getTimeout(): number {
    return this.inner.getTimeout()
  }

  /**
   * Set timeout configuration
   * @param timeoutMs - Timeout in milliseconds
   */
  setTimeout(timeoutMs: number): void {
    this.inner.setTimeout(timeoutMs)
  }

  /**
   * Get the node ID
   * @returns Current node ID
   */
  getNodeId(): string {
    return this.inner.getNodeId()
  }

  /**
   * Check if protocol is ready
   * @returns true if ready
   */
  isReady(): boolean {
    return this.inner.isReady()
  }

  /**
   * Close and cleanup protocol resources
   */
  async close(): Promise<void> {
    return this.inner.close()
  }
}

/**
 * Create a new protocol instance with default configuration
 *
 * @example
 * ```typescript
 * const protocol = createProtocol()
 * ```
 *
 * @returns New protocol instance
 */
export function createProtocol(): QuDAGProtocolClass {
  const native = nativeCreateProtocol()
  const wrapper = Object.create(QuDAGProtocolClass.prototype)
  wrapper.inner = native
  return wrapper as QuDAGProtocolClass
}

/**
 * Validate a protocol message
 * @param message - Message to validate
 * @returns true if message is valid
 */
export function validateMessage(message: ProtocolMessage): boolean {
  const nativeMessage: any = {
    messageType: message.messageType,
    sourceNode: message.sourceNode,
    destinationNode: message.destinationNode,
    payload: Buffer.isBuffer(message.payload)
      ? Array.from(message.payload)
      : Array.from(message.payload as Uint8Array),
    timestamp: message.timestamp,
  }
  return nativeValidateMessage(nativeMessage)
}

/**
 * Get protocol version information
 * @returns Version string
 */
export function getProtocolVersion(): string {
  return nativeGetProtocolVersion()
}

/**
 * Process data with default protocol instance
 * @param data - Data to process
 * @returns Processing result
 */
export function processDataDefault(data: Buffer | Uint8Array): OperationResult {
  const buffer = Buffer.isBuffer(data) ? data : Buffer.from(data)
  const result = nativeProcessDataDefault(buffer)
  return {
    success: result.success,
    message: result.message,
    data: Buffer.from(result.data),
    timestamp: result.timestamp,
  }
}

// Export the class as default for convenience
export default QuDAGProtocolClass
