/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Create default edge detection preset */
export declare function createEdgeDetectionPreset(): string
/** Create default face detection preset */
export declare function createFaceDetectionPreset(): string
/** Create default object tracking preset */
export declare function createObjectTrackingPreset(): string
/** Create default thresholding preset */
export declare function createThresholdingPreset(): string
/** Get default SDK configuration */
export declare function getDefaultSdkConfig(): string
/** OpenCV SDK - High-level computer vision API */
export declare class OpenCvSdk {
  /** Create a new OpenCV SDK instance */
  constructor(configJson?: string | undefined | null)
  /** Get SDK configuration */
  getConfig(): string
  /** Create a new image processing pipeline */
  createPipeline(pipelineJson: string): string
  /** Get pipeline by ID */
  getPipeline(pipelineId: string): string
  /** List all pipelines */
  listPipelines(): string
  /** Process image with pipeline */
  processImage(imageId: string, pipelineId: string, width: number, height: number): string
  /** Create a batch processing job */
  createBatchJob(imageIdsJson: string, pipelineId: string): string
  /** Get batch job status */
  getBatchJobStatus(jobId: string): string
  /** Process batch with progress */
  processBatch(jobId: string): string
  /** Complete batch job */
  completeBatch(jobId: string): string
  /** Register a computer vision preset */
  registerPreset(presetJson: string): string
  /** Get preset by type */
  getPreset(presetType: string): string
  /** List all presets */
  listPresets(): string
  /** Apply edge detection preset */
  applyEdgeDetection(imageId: string, method: string): string
  /** Apply blur filter preset */
  applyBlurFilter(imageId: string, kernelSize: number): string
  /** Apply color space conversion preset */
  applyColorConversion(imageId: string, colorSpace: string): string
  /** Start a workflow */
  startWorkflow(workflowConfigJson: string): string
  /** Execute next stage in workflow */
  executeWorkflowStage(workflowId: string, stageIndex: number): string
  /** Get workflow execution result */
  getWorkflowResult(workflowId: string): string
  /** Validate pipeline configuration */
  validatePipeline(pipelineJson: string): string
  /** Clear all caches */
  clearCaches(): boolean
  /** Get session ID */
  getSessionId(): string
  /** Get statistics */
  getStatistics(): string
}
