/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Calculate log return from price data */
export declare function calculateLogReturn(previousPrice: number, currentPrice: number): number
/** Calculate percentage change between two prices */
export declare function calculatePriceChange(previousPrice: number, currentPrice: number): number
/**
 * Process a single trade data point
 *
 * # Arguments
 * * `trade_data_json` - JSON string containing trade data
 *
 * # Returns
 * JSON string with processed trade data
 */
export declare function processTradeData(tradeDataJson: string): string
/**
 * Batch process multiple trade data points
 *
 * # Arguments
 * * `trade_data_array_json` - JSON array string containing multiple trade data objects
 *
 * # Returns
 * JSON array string with processed trade data
 */
export declare function batchProcessTrades(tradeDataArrayJson: string): string
/**
 * Calculate moving average from an array of prices
 *
 * # Arguments
 * * `prices_json` - JSON array of prices
 * * `window` - Window size for moving average
 *
 * # Returns
 * Moving average value
 */
export declare function calculateMovingAverage(pricesJson: string, window: number): number
/**
 * Calculate portfolio metrics
 *
 * # Arguments
 * * `portfolio_config_json` - JSON string containing portfolio configuration
 * * `trades_json` - JSON array of executed trades
 *
 * # Returns
 * JSON string with portfolio metrics
 */
export declare function calculatePortfolioMetrics(portfolioConfigJson: string, tradesJson: string): string
/**
 * Validate trade parameters
 *
 * # Arguments
 * * `symbol` - Trading symbol
 * * `price` - Trade price
 * * `volume` - Trade volume
 * * `portfolio_config_json` - JSON string containing portfolio configuration
 *
 * # Returns
 * Boolean indicating if trade is valid
 */
export declare function validateTrade(symbol: string, price: number, volume: number, portfolioConfigJson: string): boolean
/**
 * Calculate Value at Risk (VaR) at a given confidence level
 *
 * # Arguments
 * * `returns_json` - JSON array of historical returns
 * * `confidence_level` - Confidence level (0.0 to 1.0)
 *
 * # Returns
 * Value at Risk
 */
export declare function calculateVar(returnsJson: string, confidenceLevel: number): number
/**
 * Optimize position sizing based on Kelly Criterion
 *
 * # Arguments
 * * `win_probability` - Probability of winning trade
 * * `win_loss_ratio` - Ratio of average win to average loss
 *
 * # Returns
 * Optimal fraction of capital to risk
 */
export declare function calculateKellyFraction(winProbability: number, winLossRatio: number): number
