/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Analyzes text for deceptive indicators
 *
 * # Arguments
 * * `text_json` - JSON string containing text to analyze
 *
 * # Returns
 * JSON string with text analysis results
 */
export declare function analyzeText(textJson: string): string
/**
 * Analyzes audio features for deceptive indicators
 *
 * # Arguments
 * * `audio_json` - JSON string containing audio features
 *
 * # Returns
 * JSON string with audio analysis results
 */
export declare function analyzeAudio(audioJson: string): string
/**
 * Analyzes physiological data for deceptive indicators
 *
 * # Arguments
 * * `physio_json` - JSON string containing physiological data
 *
 * # Returns
 * JSON string with physiological analysis results
 */
export declare function analyzePhysiological(physioJson: string): string
/**
 * Performs comprehensive multi-modal lie detection analysis
 *
 * # Arguments
 * * `analysis_json` - JSON string containing all available analysis data
 *
 * # Returns
 * JSON string with comprehensive detection results
 */
export declare function detectDeception(analysisJson: string): string
/**
 * Compare two analyses for consistency
 *
 * # Arguments
 * * `analysis1_json` - First analysis as JSON string
 * * `analysis2_json` - Second analysis as JSON string
 *
 * # Returns
 * Consistency score (0.0 to 1.0)
 */
export declare function compareAnalyses(analysis1Json: string, analysis2Json: string): number
