/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Process a self-referential loop structure
 *
 * # Arguments
 * * `loop_json` - JSON string containing loop state
 * * `config_json` - JSON string containing configuration options
 *
 * # Returns
 * JSON string with processed loop result
 */
export declare function processStrangeLoop(loopJson: string, configJson: string): string
/**
 * Analyze meta-learning with self-referential structure
 *
 * # Arguments
 * * `context_json` - JSON string containing meta context
 *
 * # Returns
 * JSON string with meta-learning analysis
 */
export declare function analyzeMetaLearning(contextJson: string): string
/**
 * Detect strange loop patterns in data
 *
 * # Arguments
 * * `data_json` - JSON string containing data to analyze
 *
 * # Returns
 * JSON object with detected patterns
 */
export declare function detectPatterns(dataJson: string): string
/**
 * Extract self-referential layers from nested structure
 *
 * # Arguments
 * * `data_json` - JSON string containing nested structure
 *
 * # Returns
 * JSON array of extracted layers
 */
export declare function extractLayers(dataJson: string): string
/**
 * Resolve strange loop paradox with iterative approximation
 *
 * # Arguments
 * * `loop_data_json` - JSON string containing loop data
 *
 * # Returns
 * JSON object with paradox resolution
 */
export declare function resolveParadox(loopDataJson: string): string
