/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Simulate Lorenz attractor trajectory
 *
 * # Arguments
 * * `config_json` - JSON string containing simulation configuration
 * * `initial_json` - JSON string containing initial point [x, y, z]
 *
 * # Returns
 * JSON string containing trajectory data
 */
export declare function simulateLorenz(configJson: string, initialJson: string): string
/**
 * Simulate Rössler attractor trajectory
 *
 * # Arguments
 * * `config_json` - JSON string containing simulation configuration
 * * `initial_json` - JSON string containing initial point [x, y, z]
 *
 * # Returns
 * JSON string containing trajectory data
 */
export declare function simulateRossler(configJson: string, initialJson: string): string
/**
 * Compute Lyapunov exponents for a trajectory
 *
 * # Arguments
 * * `trajectory_json` - JSON string containing trajectory data
 *
 * # Returns
 * JSON string containing Lyapunov analysis results
 */
export declare function computeLyapunovExponents(trajectoryJson: string): string
/**
 * Calculate distance statistics for a trajectory
 *
 * # Arguments
 * * `trajectory_json` - JSON string containing trajectory data
 *
 * # Returns
 * JSON object with distance statistics
 */
export declare function computeTrajectoryStatistics(trajectoryJson: string): string
/**
 * Extract attractor points (after transient behavior)
 *
 * # Arguments
 * * `trajectory_json` - JSON string containing trajectory data
 * * `skip_ratio` - Ratio of initial points to skip (0.0 to 1.0)
 *
 * # Returns
 * JSON string containing filtered trajectory
 */
export declare function extractAttractorPoints(trajectoryJson: string, skipRatio: number): string
/**
 * Calculate recurrence time statistics
 *
 * # Arguments
 * * `trajectory_json` - JSON string containing trajectory data
 * * `threshold` - Distance threshold for recurrence
 *
 * # Returns
 * JSON object with recurrence statistics
 */
export declare function computeRecurrenceTime(trajectoryJson: string, threshold: number): string
