/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Generate a keypair for quantum-resistant cryptography
 *
 * # Arguments
 * * `config_json` - JSON string containing crypto configuration
 *
 * # Returns
 * JSON string with generated keypair
 */
export declare function generateKeypair(configJson: string): string
/**
 * Hash data using BLAKE3
 *
 * # Arguments
 * * `data` - Data to hash as hex string
 * * `algorithm` - Hash algorithm (blake3, sha256)
 *
 * # Returns
 * JSON string with hash result
 */
export declare function hashData(data: string, algorithm: string): string
/**
 * Sign data using quantum-resistant algorithm
 *
 * # Arguments
 * * `data` - Data to sign as hex string
 * * `private_key` - Private key as hex string
 * * `algorithm` - Signing algorithm
 *
 * # Returns
 * JSON string with signature result
 */
export declare function signData(data: string, privateKey: string, algorithm: string): string
/**
 * Verify a signature using quantum-resistant algorithm
 *
 * # Arguments
 * * `data` - Original data as hex string
 * * `signature` - Signature as hex string
 * * `public_key` - Public key as hex string
 * * `algorithm` - Signature algorithm
 *
 * # Returns
 * JSON string with verification result
 */
export declare function verifySignature(data: string, signature: string, publicKey: string, algorithm: string): string
/**
 * Encrypt data using quantum-resistant encryption
 *
 * # Arguments
 * * `plaintext` - Data to encrypt as hex string
 * * `public_key` - Public key as hex string
 * * `algorithm` - Encryption algorithm
 *
 * # Returns
 * JSON string with encryption result
 */
export declare function encryptData(plaintext: string, publicKey: string, algorithm: string): string
/**
 * Decrypt data using quantum-resistant decryption
 *
 * # Arguments
 * * `ciphertext` - Encrypted data as hex string
 * * `nonce` - Nonce used in encryption as hex string
 * * `private_key` - Private key as hex string
 * * `algorithm` - Decryption algorithm
 *
 * # Returns
 * JSON string with decryption result
 */
export declare function decryptData(ciphertext: string, nonce: string, privateKey: string, algorithm: string): string
/**
 * Get supported quantum-resistant algorithms
 *
 * # Returns
 * JSON array of supported algorithms
 */
export declare function getSupportedAlgorithms(): string
/**
 * Perform key agreement using quantum-resistant algorithm
 *
 * # Arguments
 * * `public_key_1` - First public key as hex string
 * * `public_key_2` - Second public key as hex string
 * * `algorithm` - Key agreement algorithm
 *
 * # Returns
 * Shared secret as hex string
 */
export declare function keyAgreement(publicKey1: string, publicKey2: string, algorithm: string): string
