/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Calculate attention scores between query and keys
 *
 * # Arguments
 * * `query_json` - JSON string containing query vector
 * * `keys_json` - JSON array string containing key vectors
 * * `scale_factor` - Scaling factor for scores (typically sqrt(dim))
 *
 * # Returns
 * JSON string containing attention scores
 */
export declare function calculateAttentionScores(queryJson: string, keysJson: string, scaleFactor: number): string
/**
 * Calculate context vector by aggregating attention-weighted values
 *
 * # Arguments
 * * `attention_scores_json` - JSON string containing attention scores
 * * `values_json` - JSON array string containing value vectors
 * * `aggregation_method` - Method to use: "sum", "mean", "max"
 *
 * # Returns
 * JSON string containing the aggregated context vector
 */
export declare function calculateContextVector(attentionScoresJson: string, valuesJson: string, aggregationMethod: string): string
/**
 * Compute multi-head attention for a query
 *
 * # Arguments
 * * `query_json` - JSON string containing query vector
 * * `keys_json` - JSON array string containing key vectors
 * * `values_json` - JSON array string containing value vectors
 * * `num_heads` - Number of attention heads
 * * `dimension` - Dimension of vectors
 *
 * # Returns
 * JSON string containing multi-head attention output
 */
export declare function multiHeadAttention(queryJson: string, keysJson: string, valuesJson: string, numHeads: number, dimension: number): string
/**
 * Create a CartanAttention layer with specified configuration
 *
 * # Arguments
 * * `config_json` - JSON string containing attention configuration
 *
 * # Returns
 * JSON string containing initialization result
 */
export declare function createCartanAttentionLayer(configJson: string): string
/**
 * Normalize attention scores using L2 normalization
 *
 * # Arguments
 * * `scores_json` - JSON array string containing raw scores
 *
 * # Returns
 * JSON array string containing normalized scores
 */
export declare function normalizeAttentionScores(scoresJson: string): string
/**
 * Calculate weight decay for regularization
 *
 * # Arguments
 * * `weights_json` - JSON array string containing weights
 * * `decay_factor` - Decay factor (typically 0.01)
 *
 * # Returns
 * JSON object containing decay statistics
 */
export declare function calculateWeightDecay(weightsJson: string, decayFactor: number): string
/**
 * Apply positional encoding to attention vectors
 *
 * # Arguments
 * * `vectors_json` - JSON array string containing vectors
 * * `position` - Position in sequence
 * * `dimension` - Dimension of vectors
 *
 * # Returns
 * JSON array string containing position-encoded vectors
 */
export declare function applyPositionalEncoding(vectorsJson: string, position: number, dimension: number): string
