/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Initialize the sublinear solver
 *
 * # Arguments
 * * `config_json` - JSON string containing configuration options
 *
 * # Returns
 * JSON string with initialization status
 */
export declare function initializeSolver(configJson: string): string
/**
 * Solve a linear system using sublinear algorithm
 *
 * # Arguments
 * * `matrix_json` - JSON string containing system matrix
 * * `rhs_json` - JSON string containing right-hand side vector
 *
 * # Returns
 * JSON string with solution result
 */
export declare function solveSystem(matrixJson: string, rhsJson: string): string
/**
 * Process input buffer data
 *
 * # Arguments
 * * `data` - Input buffer to process
 * * `options_json` - JSON string containing processing options
 *
 * # Returns
 * Processed buffer
 */
export declare function processBuffer(data: Array<number>, optionsJson: string): Array<number>
/**
 * Batch solve multiple systems
 *
 * # Arguments
 * * `systems_json` - JSON array string containing multiple system matrices
 * * `rhs_array_json` - JSON array string containing RHS vectors
 *
 * # Returns
 * JSON array with solution results
 */
export declare function batchSolve(systemsJson: string, rhsArrayJson: string): string
/**
 * Analyze system properties
 *
 * # Arguments
 * * `matrix_json` - JSON string containing system matrix
 *
 * # Returns
 * JSON with system analysis
 */
export declare function analyzeSystem(matrixJson: string): string
/**
 * Validate system feasibility
 *
 * # Arguments
 * * `matrix_json` - JSON string containing system matrix
 * * `rhs_json` - JSON string containing right-hand side
 *
 * # Returns
 * JSON with validation results
 */
export declare function validateSystem(matrixJson: string, rhsJson: string): string
