/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Represents the result of dimensionality estimation */
export interface DimensionalityResult {
  /** The estimated intrinsic dimension */
  dimension: number
  /** Confidence score of the estimate (0.0 - 1.0) */
  confidence: number
  /** Additional metrics */
  metrics: DimensionalityMetrics
}
/** Additional metrics for dimensionality estimation */
export interface DimensionalityMetrics {
  /** Variance ratio explained */
  varianceRatio: number
  /** Number of samples used */
  samplesUsed: number
  /** Number of features in input data */
  features: number
}
/**
 * Estimate intrinsic dimensionality from a data matrix
 *
 * # Arguments
 * - data: A 2D array where each row is a sample and each column is a feature
 *
 * # Returns
 * A DimensionalityResult containing the estimated dimension and confidence
 */
export declare function estimate(data: Array<Array<number>>): DimensionalityResult
/**
 * Estimate dimensionality using Multiple Kriged Kalman Filter (MKKF) method
 *
 * # Arguments
 * - data: A 2D array of numerical data
 * - k_max: Maximum number of nearest neighbors to consider
 *
 * # Returns
 * The estimated intrinsic dimension
 */
export declare function estimateMkkf(data: Array<Array<number>>, kMax: number): number
/**
 * Estimate dimensionality for batch data
 *
 * # Arguments
 * - data_batch: A vector of data samples, each being a vector of features
 *
 * # Returns
 * A vector of DimensionalityResult for each sample
 */
export declare function estimateBatch(dataBatch: Array<Array<Array<number>>>): Array<DimensionalityResult>
/** Get dimensionality estimation parameters and defaults */
export interface EstimationParams {
  /** Variance threshold for determining dimension (default: 0.95) */
  varianceThreshold: number
  /** Minimum samples required */
  minSamples: number
  /** Maximum features to consider */
  maxFeatures: number
}
/** Get default estimation parameters */
export declare function getDefaultParams(): EstimationParams
