/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Add position to portfolio
 *
 * # Arguments
 * * `portfolio_json` - JSON string containing portfolio data
 * * `position_json` - JSON string containing position data
 *
 * # Returns
 * JSON string with updated portfolio
 */
export declare function addPosition(portfolioJson: string, positionJson: string): string
/**
 * Remove position from portfolio
 *
 * # Arguments
 * * `portfolio_json` - JSON string containing portfolio data
 * * `symbol` - Symbol of position to remove
 *
 * # Returns
 * JSON string with updated portfolio
 */
export declare function removePosition(portfolioJson: string, symbol: string): string
/**
 * Update position with current price
 *
 * # Arguments
 * * `portfolio_json` - JSON string containing portfolio data
 * * `symbol` - Symbol to update
 * * `current_price` - New current price
 *
 * # Returns
 * JSON string with updated portfolio
 */
export declare function updatePositionPrice(portfolioJson: string, symbol: string, currentPrice: number): string
/**
 * Calculate realized P&L
 *
 * # Arguments
 * * `entry_price` - Entry price
 * * `exit_price` - Exit price
 * * `quantity` - Quantity
 * * `position_type` - "long" or "short"
 *
 * # Returns
 * Realized P&L
 */
export declare function calculateRealizedPnl(entryPrice: number, exitPrice: number, quantity: number, positionType: string): number
/**
 * Calculate unrealized P&L
 *
 * # Arguments
 * * `entry_price` - Entry price
 * * `current_price` - Current price
 * * `quantity` - Quantity
 * * `position_type` - "long" or "short"
 *
 * # Returns
 * Unrealized P&L
 */
export declare function calculateUnrealizedPnl(entryPrice: number, currentPrice: number, quantity: number, positionType: string): number
/**
 * Calculate portfolio P&L summary
 *
 * # Arguments
 * * `portfolio_json` - JSON string containing portfolio data
 *
 * # Returns
 * JSON string with P&L summary
 */
export declare function calculatePortfolioPnl(portfolioJson: string): string
/**
 * Calculate portfolio Value at Risk (VaR)
 *
 * # Arguments
 * * `portfolio_json` - JSON string containing portfolio data
 * * `confidence_level` - Confidence level (0.0 to 1.0)
 *
 * # Returns
 * VaR value
 */
export declare function calculateValueAtRisk(portfolioJson: string, confidenceLevel: number): number
/**
 * Calculate portfolio beta relative to a market index
 *
 * # Arguments
 * * `portfolio_json` - JSON string containing portfolio data
 * * `individual_betas_json` - JSON string with individual stock betas
 *
 * # Returns
 * Portfolio beta
 */
export declare function calculatePortfolioBeta(portfolioJson: string, individualBetasJson: string): number
/**
 * Calculate correlation between two portfolio allocations
 *
 * # Arguments
 * * `allocation1_json` - First allocation as JSON array
 * * `allocation2_json` - Second allocation as JSON array
 *
 * # Returns
 * Correlation coefficient (-1.0 to 1.0)
 */
export declare function calculateCorrelation(allocation1Json: string, allocation2Json: string): number
/**
 * Calculate concentration risk
 *
 * # Arguments
 * * `portfolio_json` - JSON string containing portfolio data
 *
 * # Returns
 * Concentration ratio (0.0 to 1.0)
 */
export declare function calculateConcentrationRisk(portfolioJson: string): number
/**
 * Suggest portfolio rebalancing
 *
 * # Arguments
 * * `portfolio_json` - JSON string containing portfolio data
 * * `target_allocations_json` - JSON string with target allocations
 *
 * # Returns
 * JSON string with rebalancing suggestions
 */
export declare function suggestRebalancing(portfolioJson: string, targetAllocationsJson: string): string
/**
 * Calculate Sharpe ratio for portfolio
 *
 * # Arguments
 * * `portfolio_json` - JSON string containing portfolio data
 * * `risk_free_rate` - Risk-free rate
 * * `volatility` - Portfolio volatility estimate
 *
 * # Returns
 * Sharpe ratio
 */
export declare function calculateSharpeRatio(portfolioJson: string, riskFreeRate: number, volatility: number): number
/**
 * Calculate Sortino ratio for portfolio
 *
 * # Arguments
 * * `portfolio_json` - JSON string containing portfolio data
 * * `risk_free_rate` - Risk-free rate
 * * `downside_volatility` - Downside volatility
 *
 * # Returns
 * Sortino ratio
 */
export declare function calculateSortinoRatio(portfolioJson: string, riskFreeRate: number, downsideVolatility: number): number
/**
 * Calculate maximum drawdown
 *
 * # Arguments
 * * `returns_json` - JSON array of historical returns
 *
 * # Returns
 * Maximum drawdown
 */
export declare function calculateMaxDrawdown(returnsJson: string): number
/**
 * Calculate comprehensive risk metrics
 *
 * # Arguments
 * * `portfolio_json` - JSON string containing portfolio data
 * * `risk_params_json` - JSON string with risk parameters
 *
 * # Returns
 * JSON string with risk metrics
 */
export declare function calculateRiskMetrics(portfolioJson: string, riskParamsJson: string): string
/**
 * Create a new empty portfolio
 *
 * # Arguments
 * * `portfolio_id` - Portfolio identifier
 * * `initial_cash` - Initial cash amount
 *
 * # Returns
 * JSON string with new portfolio
 */
export declare function createPortfolio(portfolioId: string, initialCash: number): string
/**
 * Get portfolio summary
 *
 * # Arguments
 * * `portfolio_json` - JSON string containing portfolio data
 *
 * # Returns
 * JSON string with portfolio summary
 */
export declare function getPortfolioSummary(portfolioJson: string): string
