/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Parse a JSON string and return the parsed object */
export declare function parse(jsonString: string): any
/** Parse a JSON stream (newline-delimited JSON) */
export declare function parseStream(jsonStream: string): any[]
/** Validate if a string is valid JSON */
export declare function isValidJson(jsonString: string): boolean
/** Get the type of a JSON value as a string */
export declare function getJsonType(jsonString: string): string
