/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Process dependent types with hash-consing for fast equality checking
 *
 * # Arguments
 * * `type_json` - JSON string containing type data
 *
 * # Returns
 * JSON string with processed type information
 */
export declare function processType(typeJson: string): string
/**
 * Check equality between two dependent types using hash-consing (150x faster)
 *
 * # Arguments
 * * `type1_json` - First type as JSON string
 * * `type2_json` - Second type as JSON string
 * * `options_json` - Equality options as JSON string
 *
 * # Returns
 * Equality result with metrics
 */
export declare function checkEquality(type1Json: string, type2Json: string, optionsJson: string): string
/**
 * Batch check equality for multiple type pairs
 *
 * # Arguments
 * * `pairs_json` - JSON array of type pairs
 *
 * # Returns
 * JSON array of equality results
 */
export declare function batchCheckEquality(pairsJson: string): string
/**
 * Unify two dependent types
 *
 * # Arguments
 * * `type1_json` - First type as JSON string
 * * `type2_json` - Second type as JSON string
 *
 * # Returns
 * Unified type or error
 */
export declare function unifyTypes(type1Json: string, type2Json: string): string
/**
 * Check if a term satisfies a dependent type
 *
 * # Arguments
 * * `term_json` - Term as JSON string
 * * `type_json` - Type as JSON string
 *
 * # Returns
 * Type checking result
 */
export declare function typeCheck(termJson: string, typeJson: string): string
