/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Standalone function: Hash data */
export declare function hashData(data: string): string
/** Standalone function: Validate peer address */
export declare function validatePeerAddress(address: string): boolean
/** Standalone function: Create protocol message */
export declare function createProtocolMessage(msgType: string, payloadJson: string): string
/** DAA Prime Core client */
export declare class DaaPrimeCore {
  /** Create a new DAA Prime Core instance */
  constructor(configJson?: string | undefined | null)
  /** Get the current configuration */
  getConfig(): string
  /** Initialize a peer connection */
  registerPeer(peerInfoJson: string): boolean
  /** List all registered peers */
  listPeers(): string
  /** Get count of connected peers */
  peerCount(): number
  /** Create and register a new model */
  createModel(modelMetadataJson: string): string
  /** List all registered models */
  listModels(): string
  /** Get a specific model by ID */
  getModel(modelId: string): string
  /** Process a protocol message */
  processMessage(messageJson: string): string
  /** Simulate training a model */
  trainModel(modelId: string, iterations: number): string
  /** Validate protocol version */
  validateVersion(version: string): boolean
  /** Generate a unique message ID */
  generateMessageId(): string
  /** Check health status */
  healthCheck(): string
}
