/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

const {
  MicroCoreClient,
  processSimple: native_process_simple,
  getVersion: native_get_version,
} = require('../index')

export interface Config {
  timeout?: number
  retries?: number
  maxConcurrency?: number
  logLevel?: string
}

export interface Stats {
  processedCount: number
  totalTimeMs: number
  averageTimeMs: number
}

/**
 * MicroCore client for semantic Cartan matrix operations
 *
 * @example
 * ```typescript
 * const client = new MicroCore({ timeout: 5000 })
 * const result = await client.process(data)
 * console.log(result)
 * ```
 */
export class MicroCore {
  private inner: any

  /**
   * Create a new MicroCore instance
   * @param config - Configuration options
   */
  constructor(config?: Config) {
    const nativeConfig = config
      ? {
          timeout: config.timeout,
          retries: config.retries,
          max_concurrency: config.maxConcurrency,
          log_level: config.logLevel,
        }
      : undefined
    this.inner = new MicroCoreClient(nativeConfig)
  }

  /**
   * Process input data asynchronously
   * @param data - Input buffer to process
   * @returns Promise resolving to processed buffer
   */
  process(data: Buffer): Promise<Buffer> {
    return Promise.resolve(this.inner.process(data))
  }

  /**
   * Process input data synchronously
   * @param data - Input buffer to process
   * @returns Processed buffer
   */
  processSync(data: Buffer): Buffer {
    return this.inner.processSync(data)
  }

  /**
   * Get statistics about the current state
   * @returns Statistics object
   */
  getStats(): Stats {
    return this.inner.getStats()
  }

  /**
   * Reset internal state
   */
  reset(): void {
    this.inner.reset()
  }

  /**
   * Close the client and release resources
   */
  close(): void {
    this.inner.close()
  }
}

/**
 * Simple processing function without client instance
 *
 * @example
 * ```typescript
 * const result = processSimple(data)
 * console.log(result)
 * ```
 *
 * @param data - Input buffer to process
 * @returns Processed buffer
 */
export function processSimple(data: Buffer): Buffer {
  return native_process_simple(data)
}

/**
 * Get the version of the native binding
 * @returns Version string
 */
export function getVersion(): string {
  return native_get_version()
}

// Export the class as default for convenience
export default MicroCore
