/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Initialize the WASM mesh with configuration
 *
 * # Arguments
 * * `config_json` - JSON string containing WASM mesh configuration
 *
 * # Returns
 * JSON string with initialization result
 */
export declare function initializeWasmMesh(configJson?: string | undefined | null): string
/**
 * Load a WASM module into the mesh
 *
 * # Arguments
 * * `module_json` - JSON string containing module configuration
 *
 * # Returns
 * JSON string with module loading result
 */
export declare function loadWasmModule(moduleJson: string): string
/**
 * Unload a WASM module from the mesh
 *
 * # Arguments
 * * `module_id` - ID of the module to unload
 *
 * # Returns
 * JSON string with module unloading result
 */
export declare function unloadWasmModule(moduleId: string): string
/**
 * Execute a WASM module
 *
 * # Arguments
 * * `module_id` - ID of the module to execute
 * * `input_json` - JSON string containing input data
 *
 * # Returns
 * JSON string with execution result
 */
export declare function executeWasmModule(moduleId: string, inputJson: string): string
/**
 * Serialize data for WASM transmission
 *
 * # Arguments
 * * `data_json` - JSON string containing data to serialize
 *
 * # Returns
 * JSON string with serialized data
 */
export declare function serializeData(dataJson: string): string
/**
 * Deserialize WASM data
 *
 * # Arguments
 * * `serialized_data_json` - JSON string containing serialized data
 *
 * # Returns
 * JSON string with deserialized data
 */
export declare function deserializeData(serializedDataJson: string): string
/**
 * Get browser compatibility info
 *
 * # Returns
 * JSON string with browser API compatibility information
 */
export declare function getBrowserCompatibility(): string
/**
 * Get performance metrics for the WASM mesh
 *
 * # Arguments
 * * `module_id` - ID of the module to get metrics for
 *
 * # Returns
 * JSON string with performance metrics
 */
export declare function getPerformanceMetrics(moduleId: string): string
/**
 * Batch load multiple WASM modules
 *
 * # Arguments
 * * `modules_json` - JSON array of module configurations
 *
 * # Returns
 * JSON string with batch load result
 */
export declare function batchLoadModules(modulesJson: string): string
/**
 * Validate WASM module before loading
 *
 * # Arguments
 * * `module_json` - JSON string containing module configuration
 *
 * # Returns
 * JSON string with validation result
 */
export declare function validateWasmModule(moduleJson: string): string
