/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Main metrics collector */
export declare class MetricsCollector {
  /** Create a new metrics collector */
  constructor()
  /** Increment a counter by value */
  incrementCounter(name: string, value: number): void
  /** Get counter value */
  getCounter(name: string): number
  /** Reset a counter */
  resetCounter(name: string): void
  /** Record a value in histogram */
  recordHistogram(name: string, value: number): void
  /** Get histogram statistics */
  getHistogramStats(name: string): string
  /** Set gauge value */
  setGauge(name: string, value: number): void
  /** Get gauge value */
  getGauge(name: string): number
  /** Increment gauge */
  incrementGauge(name: string, delta: number): void
  /** Decrement gauge */
  decrementGauge(name: string, delta: number): void
  /** Get all counters */
  getAllCounters(): string
  /** Get all gauges */
  getAllGauges(): string
  /** Generate metrics report */
  generateReport(): string
  /** Clear all metrics */
  clearAll(): void
  /** Get count of all metrics */
  countMetrics(): number
}
