/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Initialize transport manager
 *
 * # Arguments
 * * `config_json` - JSON string with transport configuration
 *
 * # Returns
 * Transport manager instance ID
 */
export declare function initTransportManager(configJson: string): string
/**
 * Register a connection
 *
 * # Arguments
 * * `connection_json` - JSON string with connection details
 *
 * # Returns
 * Connection ID
 */
export declare function registerConnection(connectionJson: string): string
/**
 * Send a message through the transport layer
 *
 * # Arguments
 * * `message_json` - JSON string with message details
 *
 * # Returns
 * Message ID if sent successfully
 */
export declare function sendMessage(messageJson: string): string
/**
 * Create a message
 *
 * # Arguments
 * * `source` - Source address
 * * `destination` - Destination address
 * * `payload` - Message payload
 * * `protocol` - Protocol type
 * * `priority` - Priority level
 *
 * # Returns
 * JSON string with message details
 */
export declare function createMessage(source: string, destination: string, payload: string, protocol: string, priority: string): string
/**
 * Register a route for message delivery
 *
 * # Arguments
 * * `route_json` - JSON string with route details
 *
 * # Returns
 * Route ID
 */
export declare function registerRoute(routeJson: string): string
/**
 * Get all registered routes
 *
 * # Returns
 * JSON array of routes
 */
export declare function listRoutes(): string
/**
 * Update route configuration
 *
 * # Arguments
 * * `destination` - Route destination
 * * `config_json` - JSON string with new configuration
 *
 * # Returns
 * Updated route info
 */
export declare function updateRoute(destination: string, configJson: string): string
/**
 * Remove a route
 *
 * # Arguments
 * * `_destination` - Route destination to remove
 *
 * # Returns
 * Success status
 */
export declare function removeRoute(destination: string): boolean
/**
 * Set serialization format for protocol
 *
 * # Arguments
 * * `protocol` - Protocol name
 * * `format` - Serialization format (json, msgpack, protobuf, etc.)
 *
 * # Returns
 * Success status
 */
export declare function setSerializationFormat(protocol: string, format: string): boolean
/**
 * Get active connections
 *
 * # Returns
 * JSON array of active connections
 */
export declare function getActiveConnections(): string
/**
 * Handle incoming message
 *
 * # Arguments
 * * `message_json` - JSON string with message details
 *
 * # Returns
 * Processed message result
 */
export declare function handleIncomingMessage(messageJson: string): string
/**
 * Batch send multiple messages
 *
 * # Arguments
 * * `messages_json` - JSON array of messages
 *
 * # Returns
 * JSON array with send results
 */
export declare function batchSendMessages(messagesJson: string): string
/**
 * Close a connection
 *
 * # Arguments
 * * `connection_id` - Connection ID to close
 *
 * # Returns
 * Success status
 */
export declare function closeConnection(connectionId: string): boolean
/**
 * Get transport statistics
 *
 * # Returns
 * JSON with transport stats
 */
export declare function getTransportStats(): string
/**
 * Get connection statistics
 *
 * # Returns
 * JSON with connection stats
 */
export declare function getConnectionStats(): string
/**
 * Enable protocol
 *
 * # Arguments
 * * `protocol` - Protocol to enable
 *
 * # Returns
 * Success status
 */
export declare function enableProtocol(protocol: string): boolean
/**
 * Disable protocol
 *
 * # Arguments
 * * `protocol` - Protocol to disable
 *
 * # Returns
 * Success status
 */
export declare function disableProtocol(protocol: string): boolean
/**
 * Get enabled protocols
 *
 * # Returns
 * JSON array of enabled protocols
 */
export declare function getEnabledProtocols(): string
/**
 * Serialize message with specified format
 *
 * # Arguments
 * * `message_json` - JSON message
 * * `format` - Format type (json, compact, etc.)
 *
 * # Returns
 * Serialized message
 */
export declare function serializeMessage(messageJson: string, format: string): string
/**
 * Deserialize message
 *
 * # Arguments
 * * `serialized_data` - Serialized message data
 * * `format` - Format type
 *
 * # Returns
 * Deserialized message
 */
export declare function deserializeMessage(serializedData: string, format: string): string
/** Main transport manager for RUV swarm communication */
export declare class TransportManager {
  constructor()
  getId(): string
  sendMessage(messageJson: string): string
  registerConnection(connectionJson: string): string
  registerRoute(routeJson: string): string
  listRoutes(): string
  removeRoute(destination: string): boolean
  getConnections(): string
  closeConnection(connectionId: string): boolean
  getTransportStats(): string
  getConnectionStats(): string
  enableProtocol(protocol: string): boolean
  disableProtocol(protocol: string): boolean
  getEnabledProtocols(): string
}
