/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

const { TemporalNeuralSolver, processDefault, processDetailed, getVersion } = require('../index')

export interface Config {
  timeout?: number
  retries?: number
  logLevel?: string
  maxConcurrency?: number
}

export interface ProcessResult {
  success: boolean
  data?: Buffer
  error?: string
}

/**
 * TemporalNeuralSolver class for ultra-fast neural network inference
 *
 * @example
 * ```typescript
 * const solver = new TemporalNeuralSolver({
 *   timeout: 5000,
 *   retries: 3
 * })
 * const result = await solver.process(Buffer.from('test data'))
 * await solver.close()
 * ```
 */
export class TemporalNeuralSolverClass {
  private inner: any

  /**
   * Create a new TemporalNeuralSolver instance with optional configuration
   * @param config - Optional configuration object
   */
  constructor(config?: Config) {
    this.inner = new TemporalNeuralSolver(config)
  }

  /**
   * Process input data
   * @param data - Input buffer to process
   * @returns Processed buffer
   */
  process(data: Buffer): Buffer {
    return this.inner.process(data)
  }

  /**
   * Process input data synchronously
   * @param data - Input buffer to process
   * @returns Processed buffer
   */
  processSync(data: Buffer): Buffer {
    return this.inner.processSync(data)
  }

  /**
   * Get current configuration
   * @returns Configuration object
   */
  getConfig(): Config {
    return this.inner.getConfig()
  }

  /**
   * Check if the solver is ready
   * @returns True if ready, false otherwise
   */
  isReady(): boolean {
    return this.inner.isReady()
  }

  /**
   * Close the solver and release resources
   */
  close(): void {
    return this.inner.close()
  }
}

/**
 * Process data with default settings
 *
 * @example
 * ```typescript
 * const result = process(Buffer.from('test data'))
 * ```
 *
 * @param data - Input buffer to process
 * @returns Processed buffer
 */
export function process(data: Buffer): Buffer {
  return processDefault(data)
}

/**
 * Process data synchronously with default settings
 *
 * @param data - Input buffer to process
 * @returns Processed buffer
 */
export function processSync(data: Buffer): Buffer {
  return processDefault(data)
}

/**
 * Process with detailed result object
 *
 * @example
 * ```typescript
 * const result = await processDetailed(Buffer.from('test data'))
 * if (result.success) {
 *   console.log('Success:', result.data)
 * } else {
 *   console.error('Error:', result.error)
 * }
 * ```
 *
 * @param data - Input buffer to process
 * @returns Promise resolving to detailed result object
 */
export function processWithResult(data: Buffer): ProcessResult {
  return processDetailed(data)
}

/**
 * Get the version of the package
 *
 * @returns Version string
 */
export function version(): string {
  return getVersion()
}

// Export the class as default for convenience
export default TemporalNeuralSolverClass
