/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Initialize a new MeshCli instance with configuration
 *
 * # Arguments
 * * `config_json` - JSON string containing mesh configuration
 *
 * # Returns
 * JSON string with initialization result
 */
export declare function initializeMeshCli(configJson: string): string
/**
 * Execute a CLI command
 *
 * # Arguments
 * * `command_json` - JSON string containing command data
 *
 * # Returns
 * JSON string with command execution result
 */
export declare function executeCommand(commandJson: string): string
/**
 * Execute multiple commands in sequence
 *
 * # Arguments
 * * `commands_json` - JSON array of commands
 *
 * # Returns
 * JSON array with execution results
 */
export declare function executeBatchCommands(commandsJson: string): string
/**
 * Get list of available commands
 *
 * # Arguments
 * * `category` - Optional category filter (e.g., "mesh", "config", "viz")
 *
 * # Returns
 * JSON array of available commands
 */
export declare function listAvailableCommands(category?: string | undefined | null): string
/**
 * Get help for a specific command
 *
 * # Arguments
 * * `command_name` - Name of the command
 *
 * # Returns
 * JSON string with help information
 */
export declare function getCommandHelp(commandName: string): string
/**
 * Generate mesh visualization
 *
 * # Arguments
 * * `nodes_json` - JSON array of mesh nodes
 * * `format` - Visualization format (e.g., "svg", "json")
 *
 * # Returns
 * JSON string with visualization data
 */
export declare function generateMeshVisualization(nodesJson: string, format: string): string
/**
 * Get current mesh CLI status
 *
 * # Returns
 * JSON string with CLI status
 */
export declare function getCliStatus(): string
/**
 * Create or update CLI configuration
 *
 * # Arguments
 * * `config_json` - JSON string containing configuration
 *
 * # Returns
 * JSON string with configuration result
 */
export declare function configureCli(configJson: string): string
/**
 * Export current mesh state
 *
 * # Arguments
 * * `export_format` - Format for export (e.g., "json", "yaml")
 *
 * # Returns
 * JSON string with exported mesh state
 */
export declare function exportMeshState(exportFormat: string): string
/**
 * Import mesh state from data
 *
 * # Arguments
 * * `import_data` - JSON string with mesh state data
 *
 * # Returns
 * JSON string with import result
 */
export declare function importMeshState(importData: string): string
/** MeshCli - Main CLI runner for code mesh operations */
export declare class MeshCli {
  /** Create a new MeshCli instance */
  constructor(configJson?: string | undefined | null)
  /** Initialize the mesh CLI */
  initialize(configJson: string): string
  /** Execute a command and track in history */
  execute(commandJson: string): string
  /** Get command history */
  getHistory(): string
  /** Get session state */
  getSessionState(): string
  /** Get current configuration */
  getConfig(): string
}
