/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** RUV Swarm Core client for orchestration */
export declare class RuvSwarmCore {
  /** Create a new RuvSwarmCore instance with optional configuration */
  constructor(config?: object | undefined | null)
  /**
   * Process data (as base64 strings)
   *
   * # Arguments
   * * `data` - Input data as base64 string
   *
   * # Returns
   * Processed data as base64 string
   */
  process(data: string): string
  /**
   * Process data synchronously
   *
   * # Arguments
   * * `data` - Input data as base64 string
   *
   * # Returns
   * Processed data as base64 string
   */
  processSync(data: string): string
  /** Close the client and release resources */
  close(): void
  /** Get configuration as JSON string */
  getConfig(): string
  /**
   * Initialize swarm agent
   *
   * # Arguments
   * * `agent_id` - Unique identifier for the agent
   * * `agent_config` - Agent configuration as JSON string
   *
   * # Returns
   * JSON string with agent initialization result
   */
  initializeAgent(agentId: string, agentConfig: string): string
  /**
   * Coordinate agents for swarm orchestration
   *
   * # Arguments
   * * `agents_json` - JSON array of agent definitions
   * * `strategy` - Orchestration strategy (e.g., "distributed", "centralized")
   *
   * # Returns
   * JSON string with orchestration result
   */
  orchestrateAgents(agentsJson: string, strategy: string): string
  /**
   * Execute distributed task across agents
   *
   * # Arguments
   * * `task_json` - Task definition as JSON string
   *
   * # Returns
   * JSON string with execution result
   */
  executeTask(taskJson: string): string
  /**
   * Get agent status
   *
   * # Arguments
   * * `agent_id` - Agent identifier
   *
   * # Returns
   * JSON string with agent status
   */
  getAgentStatus(agentId: string): string
  /**
   * Batch process multiple data items
   *
   * # Arguments
   * * `items_json` - JSON array of base64 encoded items
   *
   * # Returns
   * JSON array with processed items
   */
  batchProcess(itemsJson: string): string
}
