/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

const {
  StreamManager: NativeStreamManager,
  createStreamManager: nativeCreateStreamManager,
  createEventListener: nativeCreateEventListener,
  processMarketData: nativeProcessMarketData,
  validateStreamConfig: nativeValidateStreamConfig,
  formatStreamEvent: nativeFormatStreamEvent,
  parseMarketDataBatch: nativeParseMarketDataBatch,
} = require('../index');

/**
 * Market data point structure
 */
export interface MarketDataPoint {
  symbol: string;
  price: number;
  volume: number;
  timestamp: number;
  bid: number;
  ask: number;
  bidSize: number;
  askSize: number;
}

/**
 * Stream configuration
 */
export interface StreamConfig {
  url: string;
  timeout_ms?: number;
  retry_count?: number;
  buffer_size?: number;
  enable_compression?: boolean;
}

/**
 * Connection state information
 */
export interface ConnectionState {
  streamId: string;
  isConnected: boolean;
  errorCount: number;
  dataCount: number;
  lastHeartbeat: number;
  uptimeMs: number;
}

/**
 * Stream statistics
 */
export interface StreamStatistics {
  streamId: string;
  totalMessages: number;
  totalErrors: number;
  averageLatencyMs: number;
  bytesReceived: number;
  uptimeSeconds: number;
  reconnectCount: number;
}

/**
 * Stream event
 */
export interface StreamEvent {
  eventType: string;
  message: string;
  timestamp: number;
  streamId: string;
}

/**
 * Event listener
 */
export interface EventListener {
  eventType: string;
  handlerId: string;
}

/**
 * StreamManager class for real-time market data streaming
 *
 * Provides connection management, event handling, and data streaming capabilities
 * with automatic reconnection and error recovery.
 *
 * @example
 * ```typescript
 * const stream = new StreamManager('wss://stream.example.com', 5000)
 * await stream.connect()
 * stream.addMarketData('BTC/USD', 50000, 1000)
 * const state = stream.getConnectionState()
 * ```
 */
export class StreamManager {
  private inner: any;

  /**
   * Create a new StreamManager instance
   * @param url - WebSocket URL for the stream
   * @param timeout_ms - Optional timeout in milliseconds
   */
  constructor(url: string, timeout_ms?: number) {
    this.inner = new NativeStreamManager(url, timeout_ms);
  }

  /**
   * Connect to the WebSocket stream
   * @returns True if connection successful
   */
  connect(): boolean {
    return this.inner.connect();
  }

  /**
   * Disconnect from the stream
   * @returns True if disconnection successful
   */
  disconnect(): boolean {
    return this.inner.disconnect();
  }

  /**
   * Check if stream is currently connected
   * @returns True if connected
   */
  isConnected(): boolean {
    return this.inner.isConnected();
  }

  /**
   * Get the unique stream ID
   * @returns Stream identifier
   */
  getStreamId(): string {
    return this.inner.getStreamId();
  }

  /**
   * Add market data to the stream
   * @param symbol - Market symbol (e.g., 'BTC/USD')
   * @param price - Current price
   * @param volume - Trading volume
   */
  addMarketData(symbol: string, price: number, volume: number): void {
    return this.inner.addMarketData(symbol, price, volume);
  }

  /**
   * Get all buffered messages
   * @returns Array of message strings
   */
  getBufferedMessages(): string[] {
    return this.inner.getBufferedMessages();
  }

  /**
   * Clear the message buffer
   */
  clearBuffer(): void {
    return this.inner.clearBuffer();
  }

  /**
   * Get current connection state
   * @returns Connection state object
   */
  getConnectionState(): ConnectionState {
    return this.inner.getConnectionState();
  }

  /**
   * Get stream statistics
   * @returns Statistics object
   */
  getStatistics(): StreamStatistics {
    return this.inner.getStatistics();
  }

  /**
   * Reconnect to the stream with automatic retry
   * @returns True if reconnection successful
   */
  reconnect(): boolean {
    return this.inner.reconnect();
  }

  /**
   * Subscribe to a market symbol
   * @param symbol - Market symbol to subscribe to
   */
  subscribe(symbol: string): void {
    return this.inner.subscribe(symbol);
  }

  /**
   * Unsubscribe from a market symbol
   * @param symbol - Market symbol to unsubscribe from
   */
  unsubscribe(symbol: string): void {
    return this.inner.unsubscribe(symbol);
  }

  /**
   * Send heartbeat ping to keep connection alive
   */
  heartbeat(): void {
    return this.inner.heartbeat();
  }

  /**
   * Get current buffer size (number of messages)
   * @returns Number of messages in buffer
   */
  getBufferSize(): number {
    return this.inner.getBufferSize();
  }

  /**
   * Reset error count
   */
  resetErrorCount(): void {
    return this.inner.resetErrorCount();
  }

  /**
   * Get current error count
   * @returns Number of errors
   */
  getErrorCount(): number {
    return this.inner.getErrorCount();
  }

  /**
   * Get current data count
   * @returns Number of data points received
   */
  getDataCount(): number {
    return this.inner.getDataCount();
  }

  /**
   * Add multiple market data points in batch
   * @param dataJson - JSON string array of market data objects
   * @returns Number of items added
   */
  batchAddMarketData(dataJson: string): number {
    return this.inner.batchAddMarketData(dataJson);
  }

  /**
   * Get stream configuration
   * @returns Configuration JSON string
   */
  getConfig(): string {
    return this.inner.getConfig();
  }

  /**
   * Update stream configuration
   * @param configJson - Configuration JSON string
   */
  updateConfig(configJson: string): void {
    return this.inner.updateConfig(configJson);
  }

  /**
   * Get total bytes received
   * @returns Total bytes in double format
   */
  getTotalBytes(): number {
    return this.inner.getTotalBytes();
  }

  /**
   * Get reconnect count
   * @returns Number of times reconnected
   */
  getReconnectCount(): number {
    return this.inner.getReconnectCount();
  }

  /**
   * Reset all statistics
   */
  resetStatistics(): void {
    return this.inner.resetStatistics();
  }
}

/**
 * Create a new StreamManager instance
 * @param url - WebSocket URL
 * @param timeout_ms - Optional timeout in milliseconds
 * @returns New StreamManager instance
 */
export function createStreamManager(url: string, timeout_ms?: number): StreamManager {
  return new StreamManager(url, timeout_ms);
}

/**
 * Create an event listener
 * @param eventType - Type of event to listen for
 * @returns Event listener object
 */
export function createEventListener(eventType: string): EventListener {
  return nativeCreateEventListener(eventType);
}

/**
 * Process market data from JSON
 * @param dataJson - Market data JSON string
 * @returns Processed market data JSON string
 */
export function processMarketData(dataJson: string): string {
  return nativeProcessMarketData(dataJson);
}

/**
 * Validate stream configuration
 * @param configJson - Configuration JSON string
 * @returns True if configuration is valid
 */
export function validateStreamConfig(configJson: string): boolean {
  return nativeValidateStreamConfig(configJson);
}

/**
 * Format stream event
 * @param eventType - Type of event
 * @param message - Event message
 * @param streamId - Stream identifier
 * @returns Formatted event JSON string
 */
export function formatStreamEvent(
  eventType: string,
  message: string,
  streamId: string
): string {
  return nativeFormatStreamEvent(eventType, message, streamId);
}

/**
 * Parse market data batch from JSON array
 * @param dataJson - JSON array of market data objects
 * @returns Parsed market data JSON string
 */
export function parseMarketDataBatch(dataJson: string): string {
  return nativeParseMarketDataBatch(dataJson);
}

// Export the main class as default
export default StreamManager;
