/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

const {
  AnalysisEngine: NativeAnalysisEngine,
  createAnalysisEngine: nativeCreateAnalysisEngine,
  getLibraryVersion: nativeGetLibraryVersion,
} = require('../index')

/**
 * Configuration options for AIMDS Analysis Engine
 */
export interface AnalysisConfig {
  sensitivity?: number
  minConfidence?: number
  anomalyThreshold?: number
  patternWindowSize?: number
  maxThreats?: number
}

/**
 * Anomaly detection result
 */
export interface AnomalyDetectionResult {
  anomaly_score: number
  is_anomaly: boolean
  confidence: number
  details: string
}

/**
 * Pattern recognition result
 */
export interface PatternRecognitionResult {
  patterns_found: number
  matches: string[]
  total_score: number
  analysis_data: string
}

/**
 * Threat assessment result
 */
export interface ThreatAssessmentResult {
  threat_level: 'critical' | 'high' | 'medium' | 'low' | 'minimal'
  severity: number
  threat_type: string
  recommendations: string[]
  timestamp: string
}

/**
 * Comprehensive analysis result
 */
export interface ComprehensiveAnalysisResult {
  anomaly_analysis: AnomalyDetectionResult
  pattern_analysis: PatternRecognitionResult
  threat_assessment: ThreatAssessmentResult
  analysis_timestamp: string
  status: string
}

/**
 * Statistics for the analysis engine
 */
export interface EngineStatistics {
  sensitivity: number
  min_confidence: number
  anomaly_threshold: number
  pattern_window_size: number
  data_history_length: number
  anomaly_count: number
  pattern_cache_size: number
}

/**
 * AIMDS Analysis Engine for behavioral analysis and threat detection
 *
 * @example
 * ```typescript
 * const engine = new AnalysisEngine({
 *   sensitivity: 0.8,
 *   minConfidence: 0.7
 * })
 *
 * const result = engine.analyze(JSON.stringify({ data: 'sample' }))
 * console.log(result)
 * ```
 */
export class AnalysisEngine {
  private native: any

  /**
   * Create a new Analysis Engine
   * @param config - Optional configuration options
   */
  constructor(config?: AnalysisConfig) {
    const convertedConfig = config ? convertConfig(config) : undefined
    const configJson = convertedConfig
      ? JSON.stringify(convertedConfig)
      : undefined
    this.native = new NativeAnalysisEngine(configJson)
  }

  /**
   * Detect anomalies in the provided data
   * @param data - Data to analyze (as JSON string or object)
   * @returns Anomaly detection result
   */
  detectAnomalies(data: string | object): AnomalyDetectionResult {
    const dataJson = typeof data === 'string' ? data : JSON.stringify(data)
    const result = this.native.detectAnomalies(dataJson)
    return JSON.parse(result)
  }

  /**
   * Recognize patterns in the provided data
   * @param data - Data to analyze (as JSON string or object)
   * @returns Pattern recognition result
   */
  recognizePatterns(data: string | object): PatternRecognitionResult {
    const dataJson = typeof data === 'string' ? data : JSON.stringify(data)
    const result = this.native.recognizePatterns(dataJson)
    return JSON.parse(result)
  }

  /**
   * Assess threat level based on the data
   * @param data - Data to analyze (as JSON string or object)
   * @returns Threat assessment result
   */
  assessThreat(data: string | object): ThreatAssessmentResult {
    const dataJson = typeof data === 'string' ? data : JSON.stringify(data)
    const result = this.native.assessThreat(dataJson)
    return JSON.parse(result)
  }

  /**
   * Perform comprehensive analysis on provided data
   * @param data - Data to analyze (as JSON string or object)
   * @returns Comprehensive analysis result with all analyses
   */
  analyze(data: string | object): ComprehensiveAnalysisResult {
    const dataJson = typeof data === 'string' ? data : JSON.stringify(data)
    const result = this.native.analyze(dataJson)
    return JSON.parse(result)
  }

  /**
   * Get current engine statistics
   * @returns Engine statistics
   */
  getStatistics(): EngineStatistics {
    const result = this.native.getStatistics()
    return JSON.parse(result)
  }

  /**
   * Clear engine history and reset state
   */
  reset(): void {
    this.native.reset()
  }

  /**
   * Check if engine is ready and operational
   * @returns True if engine is operational
   */
  isReady(): boolean {
    return this.native.isReady()
  }

  /**
   * Get engine version
   * @returns Version string
   */
  getVersion(): string {
    return this.native.getVersion()
  }

  /**
   * Set the analysis sensitivity level (0.0 - 1.0)
   * @param sensitivity - Sensitivity level
   */
  setSensitivity(sensitivity: number): void {
    if (sensitivity < 0.0 || sensitivity > 1.0) {
      throw new Error('Sensitivity must be between 0.0 and 1.0')
    }
    this.native.setSensitivity(sensitivity)
  }

  /**
   * Get the current sensitivity level
   * @returns Current sensitivity level
   */
  getSensitivity(): number {
    return this.native.getSensitivity()
  }

  /**
   * Batch analyze multiple data items
   * @param dataArray - Array of data items to analyze
   * @returns Batch analysis result
   */
  batchAnalyze(
    dataArray: (string | object)[]
  ): {
    items_processed: number
    results: ComprehensiveAnalysisResult[]
    timestamp: string
  } {
    const jsonArray = dataArray.map(item =>
      typeof item === 'string' ? JSON.parse(item) : item
    )
    const result = this.native.batchAnalyze(JSON.stringify(jsonArray))
    return JSON.parse(result)
  }
}

/**
 * Converts camelCase config to snake_case for Rust
 */
function convertConfig(config: AnalysisConfig): any {
  return {
    sensitivity: config.sensitivity,
    min_confidence: config.minConfidence,
    anomaly_threshold: config.anomalyThreshold,
    pattern_window_size: config.patternWindowSize,
    max_threats: config.maxThreats,
  }
}

/**
 * Create a new Analysis Engine with default configuration
 *
 * @example
 * ```typescript
 * const engine = createAnalysisEngine()
 * const result = engine.analyze(JSON.stringify({ data: 'sample' }))
 * ```
 *
 * @returns A new AnalysisEngine instance
 */
export function createAnalysisEngine(): AnalysisEngine {
  const nativeEngine = nativeCreateAnalysisEngine()
  const engine = new AnalysisEngine()
  engine['native'] = nativeEngine
  return engine
}

/**
 * Get library version information
 *
 * @example
 * ```typescript
 * console.log(getLibraryVersion()) // "aimds-analysis 0.1.0"
 * ```
 *
 * @returns Version string
 */
export function getLibraryVersion(): string {
  return nativeGetLibraryVersion()
}

// Export AnalysisEngine as default for convenience
export default AnalysisEngine
