/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

const {
  TimeExpansionContext,
  calculateTimeExpansion: nativeCalculateTimeExpansion,
  calculateNestedExpansion: nativeCalculateNestedExpansion,
  calculateOptimalDilation: nativeCalculateOptimalDilation,
  processTimeBatch: nativeProcessTimeBatch,
  calculateAverageDilation: nativeCalculateAverageDilation,
  estimateConsciousnessLevel: nativeEstimateConsciousnessLevel,
} = require('../index')

export interface TimeCalculationResult {
  physicalTime: number
  subjectiveTime: number
  dilationFactor: number
  timeRatio: number
}

/**
 * TimeExpansionContext class for managing time dilation
 *
 * @example
 * ```typescript
 * const context = new TimeExpansionContextClass(2.0, 1.0, 5)
 * context.update(1000)
 * console.log(context.getElapsedSubjectiveTime()) // 2000
 * ```
 */
export class TimeExpansionContextClass {
  private inner: any

  /**
   * Create a new TimeExpansionContext
   * @param dilationFactor - The time dilation factor (multiplier)
   * @param baseFrequency - The base frequency for calculations
   * @param maxDepth - Maximum recursion depth
   */
  constructor(
    dilationFactor: number,
    baseFrequency: number,
    maxDepth: number
  ) {
    this.inner = new TimeExpansionContext(
      dilationFactor,
      baseFrequency,
      maxDepth
    )
  }

  /**
   * Update the context with elapsed physical time
   * @param elapsedMs - Elapsed time in milliseconds
   */
  update(elapsedMs: number): void {
    this.inner.update(elapsedMs)
  }

  /**
   * Get the current dilation factor
   */
  getDilationFactor(): number {
    return this.inner.getDilationFactor()
  }

  /**
   * Get the current base frequency
   */
  getBaseFrequency(): number {
    return this.inner.getBaseFrequency()
  }

  /**
   * Get elapsed physical time in milliseconds
   */
  getElapsedPhysicalTime(): number {
    return this.inner.getElapsedPhysicalTime()
  }

  /**
   * Get elapsed subjective time in milliseconds
   */
  getElapsedSubjectiveTime(): number {
    return this.inner.getElapsedSubjectiveTime()
  }

  /**
   * Get the time ratio (subjective / physical)
   */
  getTimeRatio(): number {
    return this.inner.getTimeRatio()
  }

  /**
   * Get the current state
   */
  getState(): string {
    return this.inner.getState()
  }

  /**
   * Reset the context
   */
  reset(): void {
    this.inner.reset()
  }
}

/**
 * Calculate time expansion for a given physical time
 *
 * @example
 * ```typescript
 * const result = calculateTimeExpansion(1000, 2.0)
 * console.log(result)
 * // { physical_time: 1000, subjective_time: 2000, dilation_factor: 2.0, time_ratio: 2.0 }
 * ```
 *
 * @param physicalTime - Physical time in milliseconds
 * @param dilationFactor - Time dilation factor
 * @returns Time calculation result with all metrics
 */
export function calculateTimeExpansion(
  physicalTime: number,
  dilationFactor: number
): TimeCalculationResult {
  return nativeCalculateTimeExpansion(physicalTime, dilationFactor)
}

/**
 * Calculate multi-level time expansion with depth
 *
 * @example
 * ```typescript
 * const result = calculateNestedExpansion(1000, 2.0, 3)
 * console.log(result) // 8000 (1000 * 2^3)
 * ```
 *
 * @param physicalTime - Physical time in milliseconds
 * @param baseFactor - Base dilation factor for each level
 * @param depth - Number of expansion levels
 * @returns Subjective time after nested expansion
 */
export function calculateNestedExpansion(
  physicalTime: number,
  baseFactor: number,
  depth: number
): number {
  return nativeCalculateNestedExpansion(physicalTime, baseFactor, depth)
}

/**
 * Calculate optimal dilation factor for a target time ratio
 *
 * @example
 * ```typescript
 * const dilation = calculateOptimalDilation(5.0)
 * console.log(dilation) // 5.0
 * ```
 *
 * @param targetRatio - Target subjective/physical time ratio
 * @returns Optimal dilation factor
 */
export function calculateOptimalDilation(targetRatio: number): number {
  return nativeCalculateOptimalDilation(targetRatio)
}

/**
 * Process a batch of time measurements with dilation
 *
 * @example
 * ```typescript
 * const times = [1000, 2000, 3000]
 * const dilated = processTimeBatch(times, 2.0)
 * console.log(dilated) // [2000, 4000, 6000]
 * ```
 *
 * @param times - Array of time measurements
 * @param dilationFactor - Dilation factor to apply
 * @returns Array of dilated times
 */
export function processTimeBatch(
  times: number[],
  dilationFactor: number
): number[] {
  return nativeProcessTimeBatch(times, dilationFactor)
}

/**
 * Calculate average dilation factor from measurements
 *
 * @example
 * ```typescript
 * const avg = calculateAverageDilation([1000, 2000], [2000, 4000])
 * console.log(avg) // 2.0
 * ```
 *
 * @param physicalTimes - Array of physical time measurements
 * @param subjectiveTimes - Array of subjective time measurements
 * @returns Average dilation factor
 */
export function calculateAverageDilation(
  physicalTimes: number[],
  subjectiveTimes: number[]
): number {
  return nativeCalculateAverageDilation(physicalTimes, subjectiveTimes)
}

/**
 * Estimate consciousness level based on time expansion parameters
 *
 * @example
 * ```typescript
 * const level = estimateConsciousnessLevel(4.0, 8)
 * console.log(level) // 0.3 (normalized to 0-1 range)
 * ```
 *
 * @param dilationFactor - Time dilation factor
 * @param processingDepth - Processing depth level
 * @returns Consciousness level (0.0 to 1.0)
 */
export function estimateConsciousnessLevel(
  dilationFactor: number,
  processingDepth: number
): number {
  return nativeEstimateConsciousnessLevel(dilationFactor, processingDepth)
}

// Export the class as default for convenience
export default TimeExpansionContextClass
