/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Create OHLCV data point
 *
 * # Arguments
 * * `ohlcv_json` - JSON string containing OHLCV data
 *
 * # Returns
 * JSON string with OHLCV data
 */
export declare function createOhlcv(ohlcvJson: string): string
/**
 * Process OHLCV data batch
 *
 * # Arguments
 * * `ohlcv_batch_json` - JSON array of OHLCV data
 *
 * # Returns
 * JSON string with aggregated statistics
 */
export declare function processOhlcvBatch(ohlcvBatchJson: string): string
/**
 * Process quote data (bid/ask)
 *
 * # Arguments
 * * `quote_json` - JSON string containing quote data
 *
 * # Returns
 * JSON string with processed quote and spread
 */
export declare function processQuote(quoteJson: string): string
/**
 * Process batch of quotes
 *
 * # Arguments
 * * `quotes_json` - JSON array of quote data
 *
 * # Returns
 * JSON string with processed quotes
 */
export declare function processQuoteBatch(quotesJson: string): string
/**
 * Process trade data
 *
 * # Arguments
 * * `trade_json` - JSON string containing trade data
 *
 * # Returns
 * JSON string with processed trade
 */
export declare function processTrade(tradeJson: string): string
/**
 * Process batch of trades
 *
 * # Arguments
 * * `trades_json` - JSON array of trade data
 *
 * # Returns
 * JSON string with trade statistics
 */
export declare function processTradeBatch(tradesJson: string): string
/**
 * Normalize market data from different sources
 *
 * # Arguments
 * * `raw_data_json` - JSON string with raw market data
 *
 * # Returns
 * JSON string with normalized data
 */
export declare function normalizeMarketData(rawDataJson: string): string
/**
 * Normalize batch of market data
 *
 * # Arguments
 * * `batch_json` - JSON array of market data
 *
 * # Returns
 * JSON array with normalized data
 */
export declare function normalizeBatch(batchJson: string): string
/**
 * Ingest real-time market data
 *
 * # Arguments
 * * `data_json` - JSON array of market data points
 *
 * # Returns
 * JSON string with ingestion statistics
 */
export declare function ingestRealtimeData(dataJson: string): string
/**
 * Ingest historical market data
 *
 * # Arguments
 * * `data_json` - JSON array of historical market data
 *
 * # Returns
 * JSON string with ingestion statistics
 */
export declare function ingestHistoricalData(dataJson: string): string
/**
 * Create cache entry
 *
 * # Arguments
 * * `cache_entry_json` - JSON string with cache data
 *
 * # Returns
 * JSON string with cache entry
 */
export declare function cacheMarketData(cacheEntryJson: string): string
/**
 * Get cache statistics
 *
 * # Arguments
 * * `cache_size` - Total number of cache entries
 * * `hits` - Number of cache hits
 * * `misses` - Number of cache misses
 *
 * # Returns
 * JSON string with cache statistics
 */
export declare function getCacheStats(cacheSize: number, hits: number, misses: number): string
/**
 * Invalidate expired cache entries
 *
 * # Arguments
 * * `entries_json` - JSON array of cache entries
 *
 * # Returns
 * JSON string with invalidation statistics
 */
export declare function invalidateExpiredCache(entriesJson: string): string
/**
 * Create buffer for streaming data
 *
 * # Arguments
 * * `symbol` - Market symbol
 * * `max_size` - Maximum buffer size
 *
 * # Returns
 * JSON string with buffer info
 */
export declare function createBuffer(symbol: string, maxSize: number): string
/**
 * Add data to buffer
 *
 * # Arguments
 * * `buffer_info_json` - Current buffer info
 * * `data_points` - Number of data points being added
 *
 * # Returns
 * JSON string with updated buffer info
 */
export declare function addToBuffer(bufferInfoJson: string, dataPoints: number): string
/**
 * Flush buffer and get data
 *
 * # Arguments
 * * `buffer_info_json` - Buffer info
 *
 * # Returns
 * JSON string with flushed buffer data
 */
export declare function flushBuffer(bufferInfoJson: string): string
