/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Initialize a new swarm mesh with configuration
 *
 * # Arguments
 * * `config_json` - JSON string containing swarm configuration
 *
 * # Returns
 * JSON string with initialized swarm info
 */
export declare function initializeSwarm(configJson?: string | undefined | null): string
/**
 * Add a node to the swarm mesh
 *
 * # Arguments
 * * `node_json` - JSON string containing node data
 *
 * # Returns
 * JSON string with node registration result
 */
export declare function addNode(nodeJson: string): string
/**
 * Remove a node from the swarm mesh
 *
 * # Arguments
 * * `node_id` - ID of the node to remove
 *
 * # Returns
 * JSON string with removal result
 */
export declare function removeNode(nodeId: string): string
/**
 * Submit a task to the swarm for execution
 *
 * # Arguments
 * * `task_json` - JSON string containing task data
 *
 * # Returns
 * JSON string with task submission result
 */
export declare function submitTask(taskJson: string): string
/**
 * Execute a task on the swarm
 *
 * # Arguments
 * * `task_json` - JSON string containing task data
 *
 * # Returns
 * JSON string with execution result
 */
export declare function executeTask(taskJson: string): string
/**
 * Get the status of the swarm mesh
 *
 * # Returns
 * JSON string with swarm status information
 */
export declare function getSwarmStatus(): string
/**
 * Distribute tasks across the swarm
 *
 * # Arguments
 * * `tasks_json` - JSON array of tasks
 * * `distribution_strategy` - Strategy for task distribution
 *
 * # Returns
 * JSON string with distribution result
 */
export declare function distributeTasks(tasksJson: string, distributionStrategy: string): string
/**
 * Get task execution history
 *
 * # Arguments
 * * `node_id` - ID of the node to get history for
 *
 * # Returns
 * JSON array of task execution records
 */
export declare function getTaskHistory(nodeId: string): string
/**
 * Perform health check on a node
 *
 * # Arguments
 * * `node_id` - ID of the node to check
 *
 * # Returns
 * JSON string with health check result
 */
export declare function healthCheck(nodeId: string): string
/**
 * Balance load across swarm nodes
 *
 * # Arguments
 * * `rebalance_strategy` - Strategy for load balancing
 *
 * # Returns
 * JSON string with rebalancing result
 */
export declare function balanceLoad(rebalanceStrategy: string): string
