/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Initialize coordinator with configuration
 *
 * # Arguments
 * * `config_json` - JSON string containing coordinator configuration
 *
 * # Returns
 * JSON string with initialization result
 */
export declare function initializeCoordinator(configJson: string): string
/**
 * Register a new agent with the coordinator
 *
 * # Arguments
 * * `agent_json` - JSON string containing agent information
 *
 * # Returns
 * JSON string with registration confirmation
 */
export declare function registerAgent(agentJson: string): string
/**
 * Get all registered agents
 *
 * # Arguments
 * * `status_filter` - Optional status filter (ACTIVE, IDLE, BUSY, FAILED, SHUTDOWN)
 *
 * # Returns
 * JSON array of agents
 */
export declare function getAgents(statusFilter?: string | undefined | null): string
/**
 * Distribute a task to the least loaded agent
 *
 * # Arguments
 * * `task_json` - JSON string containing task information
 *
 * # Returns
 * JSON string with task distribution result
 */
export declare function distributeTask(taskJson: string): string
/**
 * Distribute multiple tasks with load balancing
 *
 * # Arguments
 * * `tasks_json` - JSON array string containing task objects
 *
 * # Returns
 * JSON array with distribution results
 */
export declare function distributeTasks(tasksJson: string): string
/**
 * Initiate consensus protocol for decision-making
 *
 * # Arguments
 * * `proposal_json` - JSON string containing proposal details
 * * `agent_ids_json` - JSON array string of agent IDs to vote
 *
 * # Returns
 * JSON string with consensus result
 */
export declare function initiateConsensus(proposalJson: string, agentIdsJson: string): string
/**
 * Submit a vote for consensus
 *
 * # Arguments
 * * `vote_json` - JSON string containing vote information
 *
 * # Returns
 * JSON string with vote confirmation
 */
export declare function submitVote(voteJson: string): string
/**
 * Calculate consensus from multiple votes
 *
 * # Arguments
 * * `votes_json` - JSON array string of vote objects
 *
 * # Returns
 * JSON string with consensus result
 */
export declare function calculateConsensus(votesJson: string): string
/**
 * Get coordinator status
 *
 * # Returns
 * JSON string with current coordinator status
 */
export declare function getCoordinatorStatus(): string
/**
 * Get agent load metrics
 *
 * # Returns
 * JSON string with agent load information
 */
export declare function getAgentMetrics(): string
/**
 * Balance load across agents
 *
 * # Returns
 * JSON string with load balancing result
 */
export declare function balanceLoad(): string
/**
 * Get task distribution statistics
 *
 * # Returns
 * JSON string with distribution statistics
 */
export declare function getDistributionStats(): string
/**
 * Monitor agent health
 *
 * # Arguments
 * * `agent_id` - The agent ID to monitor
 *
 * # Returns
 * JSON string with health information
 */
export declare function monitorAgentHealth(agentId: string): string
/**
 * Scale agent pool
 *
 * # Arguments
 * * `action_json` - JSON string containing scale action details
 *
 * # Returns
 * JSON string with scaling result
 */
export declare function scaleAgentPool(actionJson: string): string
/**
 * Perform failover for a failed agent
 *
 * # Arguments
 * * `failed_agent_id` - The ID of the failed agent
 *
 * # Returns
 * JSON string with failover result
 */
export declare function performFailover(failedAgentId: string): string
/**
 * Get consensus voting history
 *
 * # Returns
 * JSON array with recent votes
 */
export declare function getVotingHistory(): string
