/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Neural Engine for managing models */
export declare class NeuralEngine {
  constructor()
  /** Create and initialize a new model */
  createModel(modelId: string, configJson: string): string
  /** Get model information */
  getModelInfo(modelId: string): string
  /** Perform model inference */
  predict(modelId: string, inputJson: string): string
  /** Batch prediction */
  predictBatch(modelId: string, inputsJson: string): string
  /** Train model */
  train(modelId: string, trainingDataJson: string, optionsJson: string): string
  /** Save model checkpoint */
  saveCheckpoint(modelId: string, checkpointName: string): string
  /** Load checkpoint */
  loadCheckpoint(modelId: string, version: number): string
  /** List checkpoints */
  listCheckpoints(modelId: string): string
  /** Optimize model hyperparameters */
  optimizeHyperparameters(modelId: string, optimizationParamsJson: string): string
  /** Delete model */
  deleteModel(modelId: string): string
  /** List all models */
  listModels(): string
  /** Evaluate model */
  evaluate(modelId: string, testDataJson: string): string
}
