/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Transpile CUDA code to Rust
 *
 * # Arguments
 * * `cuda_code` - CUDA code as a string
 *
 * # Returns
 * JSON string with transpilation result
 */
export declare function transpileCudaToRust(cudaCode: string): string
/**
 * Process CUDA code with configuration options
 *
 * # Arguments
 * * `cuda_code` - CUDA code to process
 * * `config_json` - JSON configuration string
 *
 * # Returns
 * JSON string with processing result
 */
export declare function processCudaCode(cudaCode: string, configJson: string): string
/**
 * Batch process multiple CUDA files
 *
 * # Arguments
 * * `cuda_files_json` - JSON array of CUDA code strings
 *
 * # Returns
 * JSON array of transpilation results
 */
export declare function batchTranspileCuda(cudaFilesJson: string): string
/**
 * Validate CUDA code syntax
 *
 * # Arguments
 * * `cuda_code` - CUDA code to validate
 *
 * # Returns
 * JSON with validation result
 */
export declare function validateCudaCode(cudaCode: string): string
/**
 * Get transpilation statistics
 *
 * # Arguments
 * * `stats_json` - Previous statistics as JSON
 *
 * # Returns
 * Updated statistics as JSON
 */
export declare function getTranspilationStats(statsJson: string): string
export declare class CudaClient {
  constructor(configJson?: string | undefined | null)
  transpile(cudaCode: string): string
  getStats(): string
}
