/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Parse and validate a command line */
export declare function parseAndValidateCommand(commandLine: string): string
/** Build a command from components */
export declare function buildCommand(name: string, argsJson: string, optionsJson: string): string
/** Execute a simple command by name */
export declare function executeSimpleCommand(commandName: string): string
/** Validate configuration */
export declare function validateCliConfig(configJson: string): string
/** Get default CLI configuration */
export declare function getDefaultConfig(): string
/** Generate a REPL session ID */
export declare function generateSessionId(): string
/** CLI Runner for command parsing and execution */
export declare class CliRunner {
  /** Create a new CLI runner instance */
  constructor(configJson?: string | undefined | null)
  /** Get current CLI configuration */
  getConfig(): string
  /** Parse a command string into a Command struct */
  parseCommand(commandLine: string): string
  /** Execute a command and return result */
  executeCommand(commandJson: string): string
  /** Execute a raw command line */
  executeRaw(commandLine: string): string
  /** Get command history */
  getHistory(): string
  /** Clear command history */
  clearHistory(): boolean
  /** Get current session state */
  getSessionState(): string
  /** List available commands */
  listCommands(): string
  /** Validate and update configuration */
  validateConfig(configJson: string): string
}
