/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface Config {
  timeout?: number
  retries?: number
  logLevel?: string
  maxConcurrency?: number
}
/** Process neural data with default settings */
export declare function processDefault(data: Buffer): Buffer
/** Get package version */
export declare function getVersion(): string
export interface ProcessResult {
  success: boolean
  data?: Array<number>
  error?: string
}
/** Process with detailed result */
export declare function processDetailed(data: Buffer): ProcessResult
export declare class TemporalNeuralSolver {
  constructor(config?: Config | undefined | null)
  /** Process input data */
  process(data: Buffer): Buffer
  /** Process input data synchronously */
  processSync(data: Buffer): Buffer
  /** Get configuration */
  getConfig(): Config
  /** Check if the solver is ready */
  isReady(): boolean
  /** Close the solver and release resources */
  close(): void
}
