/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * ============ DATA VALIDATION ============
 * Validate if a string is a valid email address
 *
 * # Arguments
 * * `email` - Email string to validate
 *
 * # Returns
 * Validation result with errors if any
 */
export declare function validateEmail(email: string): string
/**
 * Validate if a string is a valid URL
 *
 * # Arguments
 * * `url` - URL string to validate
 *
 * # Returns
 * Validation result
 */
export declare function validateUrl(url: string): string
/**
 * Validate if a number is within range
 *
 * # Arguments
 * * `value` - Number to validate
 * * `min` - Minimum allowed value
 * * `max` - Maximum allowed value
 *
 * # Returns
 * Validation result
 */
export declare function validateNumberRange(value: number, min: number, max: number): string
/**
 * Validate string length constraints
 *
 * # Arguments
 * * `value` - String to validate
 * * `min_length` - Minimum allowed length
 * * `max_length` - Maximum allowed length
 *
 * # Returns
 * Validation result
 */
export declare function validateStringLength(value: string, minLength: number, maxLength: number): string
/**
 * ============ FORMATTING UTILITIES ============
 * Format a number with specified decimal places
 *
 * # Arguments
 * * `value` - Number to format
 * * `decimal_places` - Number of decimal places
 *
 * # Returns
 * Formatted number string
 */
export declare function formatNumber(value: number, decimalPlaces: number): string
/**
 * Format currency with symbol and separators
 *
 * # Arguments
 * * `value` - Number to format
 * * `options_json` - JSON string with formatting options
 *
 * # Returns
 * Formatted currency string
 */
export declare function formatCurrency(value: number, optionsJson: string): string
/**
 * Convert bytes to human-readable format
 *
 * # Arguments
 * * `bytes` - Number of bytes
 *
 * # Returns
 * Human-readable string (B, KB, MB, GB, TB)
 */
export declare function formatBytes(bytes: number): string
/**
 * ============ CONVERSIONS ============
 * Convert string to boolean
 *
 * # Arguments
 * * `value` - String representation
 *
 * # Returns
 * Boolean value or error
 */
export declare function parseBoolean(value: string): boolean
/**
 * Convert hex string to decimal number
 *
 * # Arguments
 * * `hex_string` - Hexadecimal string (with or without 0x prefix)
 *
 * # Returns
 * Decimal number
 */
export declare function hexToDecimal(hexString: string): number
/**
 * Convert decimal number to hex string
 *
 * # Arguments
 * * `decimal_number` - Decimal number
 * * `include_prefix` - Whether to include "0x" prefix
 *
 * # Returns
 * Hex string
 */
export declare function decimalToHex(decimalNumber: number, includePrefix: boolean): string
/**
 * ============ STRING UTILITIES ============
 * Reverse a string
 *
 * # Arguments
 * * `value` - String to reverse
 *
 * # Returns
 * Reversed string
 */
export declare function reverseString(value: string): string
/**
 * Count character occurrences in a string
 *
 * # Arguments
 * * `value` - String to search in
 * * `character` - Character to count
 *
 * # Returns
 * Count of occurrences
 */
export declare function countCharacter(value: string, character: string): number
/**
 * Capitalize first letter of a string
 *
 * # Arguments
 * * `value` - String to capitalize
 *
 * # Returns
 * Capitalized string
 */
export declare function capitalizeString(value: string): string
/**
 * Remove all whitespace from a string
 *
 * # Arguments
 * * `value` - String to process
 *
 * # Returns
 * String without whitespace
 */
export declare function removeWhitespace(value: string): string
/**
 * ============ DATE/TIME UTILITIES ============
 * Get current timestamp in milliseconds
 *
 * # Returns
 * Current timestamp as i64
 */
export declare function getCurrentTimestamp(): number
/**
 * Convert timestamp to ISO 8601 string
 *
 * # Arguments
 * * `timestamp_ms` - Timestamp in milliseconds
 *
 * # Returns
 * ISO 8601 formatted date string
 */
export declare function timestampToIsoString(timestampMs: number): string
/**
 * Calculate time difference between two timestamps
 *
 * # Arguments
 * * `start_timestamp_ms` - Start timestamp in milliseconds
 * * `end_timestamp_ms` - End timestamp in milliseconds
 *
 * # Returns
 * Time difference in milliseconds
 */
export declare function timeDifference(startTimestampMs: number, endTimestampMs: number): number
/**
 * ============ NUMBER UTILITIES ============
 * Calculate percentage of a value
 *
 * # Arguments
 * * `value` - The value
 * * `total` - The total
 *
 * # Returns
 * Percentage value (0-100)
 */
export declare function calculatePercentage(value: number, total: number): number
/**
 * Calculate percentage increase
 *
 * # Arguments
 * * `original` - Original value
 * * `new_value` - New value
 *
 * # Returns
 * Percentage increase
 */
export declare function calculatePercentageIncrease(original: number, newValue: number): number
/**
 * Round number to nearest value
 *
 * # Arguments
 * * `value` - Value to round
 * * `decimal_places` - Number of decimal places
 *
 * # Returns
 * Rounded value
 */
export declare function roundNumber(value: number, decimalPlaces: number): number
/**
 * Clamp a number between min and max
 *
 * # Arguments
 * * `value` - Value to clamp
 * * `min` - Minimum value
 * * `max` - Maximum value
 *
 * # Returns
 * Clamped value
 */
export declare function clampNumber(value: number, min: number, max: number): number
/**
 * Calculate average of numbers
 *
 * # Arguments
 * * `numbers_json` - JSON array of numbers
 *
 * # Returns
 * Average value
 */
export declare function calculateAverage(numbersJson: string): number
