/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const { existsSync, readFileSync } = require('fs')
const { join } = require('path')

const { platform, arch } = process

let nativeBinding = null
let localFileExisted = false
let loadError = null

function isMusl() {
  // For Node 10
  if (!process.report || typeof process.report.getReport !== 'function') {
    try {
      const lddPath = require('child_process').execSync('which ldd').toString().trim()
      return readFileSync(lddPath, 'utf8').includes('musl')
    } catch (e) {
      return true
    }
  } else {
    const { glibcVersionRuntime } = process.report.getReport().header
    return !glibcVersionRuntime
  }
}

switch (platform) {
  case 'android':
    switch (arch) {
      case 'arm64':
        localFileExisted = existsSync(join(__dirname, 'nt_utils.android-arm64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./nt_utils.android-arm64.node')
          } else {
            nativeBinding = require('@ruv.io/nt-utils-android-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm':
        localFileExisted = existsSync(join(__dirname, 'nt_utils.android-arm-eabi.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./nt_utils.android-arm-eabi.node')
          } else {
            nativeBinding = require('@ruv.io/nt-utils-android-arm-eabi')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Android ${arch}`)
    }
    break
  case 'win32':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(
          join(__dirname, 'nt_utils.win32-x64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./nt_utils.win32-x64-msvc.node')
          } else {
            nativeBinding = require('@ruv.io/nt-utils-win32-x64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'ia32':
        localFileExisted = existsSync(
          join(__dirname, 'nt_utils.win32-ia32-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./nt_utils.win32-ia32-msvc.node')
          } else {
            nativeBinding = require('@ruv.io/nt-utils-win32-ia32-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'nt_utils.win32-arm64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./nt_utils.win32-arm64-msvc.node')
          } else {
            nativeBinding = require('@ruv.io/nt-utils-win32-arm64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Windows: ${arch}`)
    }
    break
  case 'darwin':
    localFileExisted = existsSync(join(__dirname, 'nt_utils.darwin-universal.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./nt_utils.darwin-universal.node')
      } else {
        nativeBinding = require('@ruv.io/nt-utils-darwin-universal')
      }
      break
    } catch {}
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(join(__dirname, 'nt_utils.darwin-x64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./nt_utils.darwin-x64.node')
          } else {
            nativeBinding = require('@ruv.io/nt-utils-darwin-x64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'nt_utils.darwin-arm64.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./nt_utils.darwin-arm64.node')
          } else {
            nativeBinding = require('@ruv.io/nt-utils-darwin-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on macOS: ${arch}`)
    }
    break
  case 'freebsd':
    if (arch !== 'x64') {
      throw new Error(`Unsupported architecture on FreeBSD: ${arch}`)
    }
    localFileExisted = existsSync(join(__dirname, 'nt_utils.freebsd-x64.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./nt_utils.freebsd-x64.node')
      } else {
        nativeBinding = require('@ruv.io/nt-utils-freebsd-x64')
      }
    } catch (e) {
      loadError = e
    }
    break
  case 'linux':
    switch (arch) {
      case 'x64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'nt_utils.linux-x64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./nt_utils.linux-x64-musl.node')
            } else {
              nativeBinding = require('@ruv.io/nt-utils-linux-x64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'nt_utils.linux-x64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./nt_utils.linux-x64-gnu.node')
            } else {
              nativeBinding = require('@ruv.io/nt-utils-linux-x64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'nt_utils.linux-arm64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./nt_utils.linux-arm64-musl.node')
            } else {
              nativeBinding = require('@ruv.io/nt-utils-linux-arm64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'nt_utils.linux-arm64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./nt_utils.linux-arm64-gnu.node')
            } else {
              nativeBinding = require('@ruv.io/nt-utils-linux-arm64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'nt_utils.linux-arm-musleabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./nt_utils.linux-arm-musleabihf.node')
            } else {
              nativeBinding = require('@ruv.io/nt-utils-linux-arm-musleabihf')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'nt_utils.linux-arm-gnueabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./nt_utils.linux-arm-gnueabihf.node')
            } else {
              nativeBinding = require('@ruv.io/nt-utils-linux-arm-gnueabihf')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'riscv64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'nt_utils.linux-riscv64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./nt_utils.linux-riscv64-musl.node')
            } else {
              nativeBinding = require('@ruv.io/nt-utils-linux-riscv64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'nt_utils.linux-riscv64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./nt_utils.linux-riscv64-gnu.node')
            } else {
              nativeBinding = require('@ruv.io/nt-utils-linux-riscv64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 's390x':
        localFileExisted = existsSync(
          join(__dirname, 'nt_utils.linux-s390x-gnu.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./nt_utils.linux-s390x-gnu.node')
          } else {
            nativeBinding = require('@ruv.io/nt-utils-linux-s390x-gnu')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Linux: ${arch}`)
    }
    break
  default:
    throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`)
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError
  }
  throw new Error(`Failed to load native binding`)
}

const { validateEmail, validateUrl, validateNumberRange, validateStringLength, formatNumber, formatCurrency, formatBytes, parseBoolean, hexToDecimal, decimalToHex, reverseString, countCharacter, capitalizeString, removeWhitespace, getCurrentTimestamp, timestampToIsoString, timeDifference, calculatePercentage, calculatePercentageIncrease, roundNumber, clampNumber, calculateAverage } = nativeBinding

module.exports.validateEmail = validateEmail
module.exports.validateUrl = validateUrl
module.exports.validateNumberRange = validateNumberRange
module.exports.validateStringLength = validateStringLength
module.exports.formatNumber = formatNumber
module.exports.formatCurrency = formatCurrency
module.exports.formatBytes = formatBytes
module.exports.parseBoolean = parseBoolean
module.exports.hexToDecimal = hexToDecimal
module.exports.decimalToHex = decimalToHex
module.exports.reverseString = reverseString
module.exports.countCharacter = countCharacter
module.exports.capitalizeString = capitalizeString
module.exports.removeWhitespace = removeWhitespace
module.exports.getCurrentTimestamp = getCurrentTimestamp
module.exports.timestampToIsoString = timestampToIsoString
module.exports.timeDifference = timeDifference
module.exports.calculatePercentage = calculatePercentage
module.exports.calculatePercentageIncrease = calculatePercentageIncrease
module.exports.roundNumber = roundNumber
module.exports.clampNumber = clampNumber
module.exports.calculateAverage = calculateAverage
