/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Result of time calculation */
export interface TimeCalculationResult {
  physicalTime: number
  subjectiveTime: number
  dilationFactor: number
  timeRatio: number
}
/** Calculate time dilation for a given physical time */
export declare function calculateTimeExpansion(physicalTime: number, dilationFactor: number): TimeCalculationResult
/** Calculate multi-level time expansion with depth */
export declare function calculateNestedExpansion(physicalTime: number, baseFactor: number, depth: number): number
/** Calculate optimal dilation factor for target ratio */
export declare function calculateOptimalDilation(targetRatio: number): number
/** Process a batch of time measurements */
export declare function processTimeBatch(times: Array<number>, dilationFactor: number): Array<number>
/** Calculate average dilation from a set of measurements */
export declare function calculateAverageDilation(physicalTimes: Array<number>, subjectiveTimes: Array<number>): number
/** Estimate consciousness level based on time expansion */
export declare function estimateConsciousnessLevel(dilationFactor: number, processingDepth: number): number
/** Time expansion context with state */
export declare class TimeExpansionContext {
  constructor(dilationFactor: number, baseFrequency: number, maxDepth: number)
  /** Update the context with elapsed physical time */
  update(elapsedMs: number): void
  /** Get the current dilation factor */
  getDilationFactor(): number
  /** Get the current base frequency */
  getBaseFrequency(): number
  /** Get elapsed physical time in milliseconds */
  getElapsedPhysicalTime(): number
  /** Get elapsed subjective time in milliseconds */
  getElapsedSubjectiveTime(): number
  /** Get the time ratio (subjective / physical) */
  getTimeRatio(): number
  /** Get the current state */
  getState(): string
  /** Reset the context */
  reset(): void
}
