/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

const nativeBindings = require('../index')

// ============ Interfaces ============

export interface NetworkConfig {
  layers: number[]
  activation?: string
  learning_rate?: number
  momentum?: number
}

export interface NetworkStats {
  num_layers: number
  total_neurons: number
  total_connections: number
  network_type: string
}

export interface TrainingConfig {
  epochs?: number
  batch_size?: number
  learning_rate?: number
  validation_split?: number
}

export interface TrainingResult {
  epochs_trained: number
  final_error: number
  total_time_ms: number
}

export interface PredictionResult {
  output: number[]
  confidence?: number
}

// ============ Error Classes ============

/**
 * Error class for neural network operations
 */
export class NeuralNetworkError extends Error {
  constructor(message: string, public code: string = 'NEURAL_NETWORK_ERROR') {
    super(message)
    this.name = 'NeuralNetworkError'
  }
}

// ============ Neural Network Class ============

/**
 * Neural Network class wrapper for FANN (Fast Artificial Neural Network) library
 *
 * @example
 * ```typescript
 * // Create a new neural network with 3 layers
 * const network = new NeuralNetwork({
 *   layers: [10, 20, 5],
 *   activation: 'relu'
 * })
 *
 * // Train the network
 * const trainingData = [[1, 2], [3, 4], [5, 6]]
 * await network.train(trainingData, { epochs: 100 })
 *
 * // Make predictions
 * const prediction = await network.predict([1.5, 2.5])
 * console.log(prediction)
 * ```
 */
export class NeuralNetwork {
  private inner: any

  /**
   * Create a new neural network instance
   * @param config - Network configuration with layer sizes
   * @throws {NeuralNetworkError} If configuration is invalid
   */
  constructor(config: NetworkConfig) {
    try {
      this.inner = new nativeBindings.NeuralNetwork(JSON.stringify(config))
    } catch (error) {
      throw new NeuralNetworkError(
        `Failed to create neural network: ${error instanceof Error ? error.message : String(error)}`,
        'INIT_FAILED'
      )
    }
  }

  /**
   * Get network statistics
   * @returns Network statistics including layer count and total neurons
   * @throws {NeuralNetworkError} If stats retrieval fails
   */
  async getStats(): Promise<NetworkStats> {
    try {
      const result = this.inner.getStats()
      return JSON.parse(result)
    } catch (error) {
      throw new NeuralNetworkError(
        `Failed to get network stats: ${error instanceof Error ? error.message : String(error)}`,
        'GET_STATS_FAILED'
      )
    }
  }

  /**
   * Forward pass through the network
   * @param input - Input data array
   * @returns Output from the network
   * @throws {NeuralNetworkError} If forward pass fails
   */
  async forward(input: number[]): Promise<number[]> {
    try {
      const result = this.inner.forward(JSON.stringify(input))
      return JSON.parse(result)
    } catch (error) {
      throw new NeuralNetworkError(
        `Forward pass failed: ${error instanceof Error ? error.message : String(error)}`,
        'FORWARD_FAILED'
      )
    }
  }

  /**
   * Train the network
   * @param trainingData - Array of training samples
   * @param config - Training configuration
   * @returns Training result with metrics
   * @throws {NeuralNetworkError} If training fails
   *
   * @example
   * ```typescript
   * const network = new NeuralNetwork({ layers: [10, 20, 5] })
   * const trainingData = [[1, 2], [3, 4], [5, 6]]
   * const result = await network.train(trainingData, {
   *   epochs: 100,
   *   learning_rate: 0.01
   * })
   * console.log(`Trained for ${result.epochs_trained} epochs`)
   * ```
   */
  async train(trainingData: number[][], config?: TrainingConfig): Promise<TrainingResult> {
    try {
      const trainingConfig = config || { epochs: 100 }
      const result = this.inner.train(
        JSON.stringify(trainingData),
        JSON.stringify(trainingConfig)
      )
      return JSON.parse(result)
    } catch (error) {
      throw new NeuralNetworkError(
        `Training failed: ${error instanceof Error ? error.message : String(error)}`,
        'TRAINING_FAILED'
      )
    }
  }

  /**
   * Make a prediction using the trained network
   * @param input - Input data array
   * @returns Predicted output
   * @throws {NeuralNetworkError} If prediction fails or network not trained
   *
   * @example
   * ```typescript
   * const prediction = await network.predict([1.5, 2.5])
   * console.log('Prediction:', prediction)
   * ```
   */
  async predict(input: number[]): Promise<number[]> {
    try {
      const result = this.inner.predict(JSON.stringify(input))
      return JSON.parse(result)
    } catch (error) {
      throw new NeuralNetworkError(
        `Prediction failed: ${error instanceof Error ? error.message : String(error)}`,
        'PREDICTION_FAILED'
      )
    }
  }

  /**
   * Check if the network is trained
   * @returns True if network has been trained, false otherwise
   * @throws {NeuralNetworkError} If check fails
   */
  async isTrained(): Promise<boolean> {
    try {
      return this.inner.isTrained()
    } catch (error) {
      throw new NeuralNetworkError(
        `Failed to check training status: ${error instanceof Error ? error.message : String(error)}`,
        'CHECK_TRAINED_FAILED'
      )
    }
  }

  /**
   * Save the trained network to a file
   * @param path - File path where network should be saved
   * @throws {NeuralNetworkError} If save fails
   *
   * @example
   * ```typescript
   * await network.save('./models/my_network.fann')
   * ```
   */
  async save(path: string): Promise<void> {
    try {
      return this.inner.save(path)
    } catch (error) {
      throw new NeuralNetworkError(
        `Failed to save network: ${error instanceof Error ? error.message : String(error)}`,
        'SAVE_FAILED'
      )
    }
  }

  /**
   * Load a network from a file
   * @param path - File path where network is stored
   * @returns Loaded neural network instance
   * @throws {NeuralNetworkError} If load fails
   *
   * @example
   * ```typescript
   * const network = await NeuralNetwork.load('./models/my_network.fann')
   * ```
   */
  static async load(path: string): Promise<NeuralNetwork> {
    try {
      const inner = nativeBindings.NeuralNetwork.load(path)
      const network = Object.create(NeuralNetwork.prototype)
      network.inner = inner
      return network
    } catch (error) {
      throw new NeuralNetworkError(
        `Failed to load network: ${error instanceof Error ? error.message : String(error)}`,
        'LOAD_FAILED'
      )
    }
  }

  /**
   * Batch predict multiple inputs
   * @param inputs - Array of input arrays
   * @returns Array of predictions
   * @throws {NeuralNetworkError} If batch prediction fails
   *
   * @example
   * ```typescript
   * const inputs = [[1, 2], [3, 4], [5, 6]]
   * const predictions = await network.batchPredict(inputs)
   * console.log('Predictions:', predictions)
   * ```
   */
  async batchPredict(inputs: number[][]): Promise<number[][]> {
    try {
      const result = this.inner.batchPredict(JSON.stringify(inputs))
      return JSON.parse(result)
    } catch (error) {
      throw new NeuralNetworkError(
        `Batch prediction failed: ${error instanceof Error ? error.message : String(error)}`,
        'BATCH_PREDICTION_FAILED'
      )
    }
  }
}

// ============ Utility Functions ============

/**
 * Create a new neural network instance
 * @param config - Network configuration
 * @returns New neural network
 * @throws {NeuralNetworkError} If network creation fails
 */
export function createNetwork(config: NetworkConfig): NeuralNetwork {
  return new NeuralNetwork(config)
}

/**
 * Validate network configuration
 * @param config - Configuration to validate
 * @returns True if configuration is valid
 *
 * @example
 * ```typescript
 * const isValid = validateConfig({ layers: [10, 20, 5] })
 * console.log('Config is valid:', isValid)
 * ```
 */
export function validateConfig(config: NetworkConfig): boolean {
  try {
    return nativeBindings.validateConfig(JSON.stringify(config))
  } catch {
    return false
  }
}

// ============ Exports ============

export default {
  NeuralNetwork,
  createNetwork,
  validateConfig,
  NeuralNetworkError,
}
