/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

const { BitParallelSearch, search, search_detailed } = require('../index.node')

export interface SearchResult {
  positions: number[]
  count: number
  found: boolean
}

/**
 * BitParallelSearch class for efficient string searching
 *
 * @example
 * ```typescript
 * const searcher = new BitParallelSearch('hello')
 * const positions = searcher.searchAll('hello world, hello rust')
 * console.log(positions) // [0, 13]
 * ```
 */
export class BitParallelSearchClass {
  private inner: any

  /**
   * Create a new BitParallelSearch instance with a pattern
   * @param pattern - The pattern to search for
   */
  constructor(pattern: string) {
    this.inner = new BitParallelSearch(pattern)
  }

  /**
   * Search for all occurrences of the pattern
   * @param haystack - The text to search in
   * @returns Array of positions where pattern is found
   */
  searchAll(haystack: string): number[] {
    return this.inner.search_all(haystack)
  }

  /**
   * Find the first occurrence of the pattern
   * @param haystack - The text to search in
   * @returns Position of first occurrence or null if not found
   */
  searchFirst(haystack: string): number | null {
    return this.inner.search_first(haystack)
  }

  /**
   * Count occurrences of the pattern
   * @param haystack - The text to search in
   * @returns Number of occurrences
   */
  count(haystack: string): number {
    return this.inner.count(haystack)
  }

  /**
   * Check if pattern exists in haystack
   * @param haystack - The text to search in
   * @returns True if pattern is found, false otherwise
   */
  contains(haystack: string): boolean {
    return this.inner.contains(haystack)
  }
}

/**
 * Convenient search function - search without creating a searcher instance
 *
 * @example
 * ```typescript
 * const positions = search('hello world', 'hello')
 * console.log(positions) // [0]
 * ```
 *
 * @param haystack - The text to search in
 * @param needle - The pattern to search for
 * @returns Array of positions where pattern is found
 */
export function search(haystack: string, needle: string): number[] {
  return search(haystack, needle)
}

/**
 * Detailed search function with metadata
 *
 * @example
 * ```typescript
 * const result = searchDetailed('hello world, hello rust', 'hello')
 * console.log(result)
 * // { positions: [0, 13], count: 2, found: true }
 * ```
 *
 * @param haystack - The text to search in
 * @param needle - The pattern to search for
 * @returns Search result with positions, count, and found flag
 */
export function searchDetailed(haystack: string, needle: string): SearchResult {
  return search_detailed(haystack, needle)
}

// Export the class as default for convenience
export default BitParallelSearchClass
