/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Create an image/matrix from image metadata
 *
 * # Arguments
 * * `image_json` - JSON string containing image metadata (width, height, channels, etc.)
 *
 * # Returns
 * JSON string with created image info
 */
export declare function createImage(imageJson: string): string
/**
 * Get image/matrix properties
 *
 * # Arguments
 * * `image_json` - JSON string containing image data
 *
 * # Returns
 * JSON string with image properties
 */
export declare function getImageProperties(imageJson: string): string
/**
 * Convert between color spaces
 *
 * # Arguments
 * * `image_json` - JSON string containing image data
 * * `source_color_space` - Source color space (e.g., "BGR", "RGB", "GRAY")
 * * `target_color_space` - Target color space
 *
 * # Returns
 * JSON string with conversion result
 */
export declare function convertColorSpace(imageJson: string, sourceColorSpace: string, targetColorSpace: string): string
/**
 * Get information about a color space
 *
 * # Arguments
 * * `color_space` - Name of the color space (e.g., "BGR", "RGB", "GRAY", "HSV", "YUV")
 *
 * # Returns
 * JSON string with color space information
 */
export declare function getColorSpaceInfo(colorSpace: string): string
/**
 * Resize image
 *
 * # Arguments
 * * `image_json` - JSON string containing image data
 * * `new_width` - New width in pixels
 * * `new_height` - New height in pixels
 *
 * # Returns
 * JSON string with resized image info
 */
export declare function resizeImage(imageJson: string, newWidth: number, newHeight: number): string
/**
 * Get image dimensions and aspect ratio
 *
 * # Arguments
 * * `image_json` - JSON string containing image data
 *
 * # Returns
 * JSON object with dimension information
 */
export declare function getImageDimensions(imageJson: string): string
/**
 * Batch process multiple images
 *
 * # Arguments
 * * `images_json` - JSON array string containing multiple image objects
 *
 * # Returns
 * JSON array with processed images
 */
export declare function batchProcessImages(imagesJson: string): string
/**
 * Get supported color spaces
 *
 * # Returns
 * JSON array with all supported color spaces
 */
export declare function getSupportedColorSpaces(): string
/**
 * Calculate image statistics (for simple operations)
 *
 * # Arguments
 * * `image_json` - JSON string containing image data
 *
 * # Returns
 * JSON object with statistics
 */
export declare function getImageStatistics(imageJson: string): string
