/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Main Jujutsu VCS client */
export declare class AgenticJujutsu {
  /** Create a new Jujutsu client instance */
  constructor(config?: object | undefined | null)
  /**
   * Initialize a new Jujutsu repository
   *
   * # Arguments
   * * `bare` - Whether to create a bare repository
   *
   * # Returns
   * JSON string with initialization result
   */
  init(bare?: boolean | undefined | null): string
  /**
   * Check if repository is initialized
   *
   * # Returns
   * Boolean indicating initialization status
   */
  isInitialized(): boolean
  /**
   * Get current repository status
   *
   * # Returns
   * JSON string with repository status
   */
  status(): string
  /**
   * Create a new revision/commit
   *
   * # Arguments
   * * `message` - Commit message
   * * `author` - Author name (optional)
   *
   * # Returns
   * JSON string with revision information
   */
  createRevision(message: string, author?: string | undefined | null): string
  /**
   * Get revision history
   *
   * # Arguments
   * * `limit` - Maximum number of revisions to return
   *
   * # Returns
   * JSON array string with revision history
   */
  getHistory(limit: number): string
  /**
   * Switch to a different branch
   *
   * # Arguments
   * * `branch_name` - Name of the branch to switch to
   * * `create` - Whether to create the branch if it doesn't exist
   *
   * # Returns
   * JSON string with switch result
   */
  switchBranch(branchName: string, create?: boolean | undefined | null): string
  /**
   * Get current branch name
   *
   * # Returns
   * Current branch name
   */
  currentBranch(): string
  /**
   * Stage files for commit
   *
   * # Arguments
   * * `files_json` - JSON array of file paths
   *
   * # Returns
   * JSON string with staging result
   */
  stageFiles(filesJson: string): string
  /**
   * Merge two branches
   *
   * # Arguments
   * * `source_branch` - Branch to merge from
   * * `options_json` - Operation options as JSON string
   *
   * # Returns
   * JSON string with merge result
   */
  merge(sourceBranch: string, optionsJson?: string | undefined | null): string
  /**
   * Sync with remote repository
   *
   * # Arguments
   * * `remote_url` - URL of remote repository
   * * `options_json` - Operation options as JSON string
   *
   * # Returns
   * JSON string with sync result
   */
  sync(remoteUrl: string, optionsJson?: string | undefined | null): string
  /**
   * Get latest revision
   *
   * # Returns
   * JSON string with latest revision information
   */
  getHead(): string
  /**
   * Get repository configuration
   *
   * # Returns
   * JSON string with configuration
   */
  getConfig(): string
  /**
   * Check if working directory is clean
   *
   * # Returns
   * Boolean indicating if working directory is clean
   */
  isClean(): boolean
  /**
   * Reset all modifications
   *
   * # Arguments
   * * `hard` - Whether to do a hard reset
   *
   * # Returns
   * JSON string with reset result
   */
  reset(hard?: boolean | undefined | null): string
}
