/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Create a new agent with the given configuration
 *
 * # Arguments
 * * `config_json` - JSON string containing agent configuration
 *
 * # Returns
 * JSON object with created agent information
 */
export declare function createAgent(configJson: string): string
/**
 * Start an agent (transition to active state)
 *
 * # Arguments
 * * `agent_id` - Agent identifier
 *
 * # Returns
 * JSON object with updated agent information
 */
export declare function startAgent(agentId: string): string
/**
 * Stop an agent
 *
 * # Arguments
 * * `agent_id` - Agent identifier
 *
 * # Returns
 * JSON object with updated agent information
 */
export declare function stopAgent(agentId: string): string
/**
 * Pause an agent
 *
 * # Arguments
 * * `agent_id` - Agent identifier
 *
 * # Returns
 * JSON object with updated agent information
 */
export declare function pauseAgent(agentId: string): string
/**
 * Resume a paused agent
 *
 * # Arguments
 * * `agent_id` - Agent identifier
 *
 * # Returns
 * JSON object with updated agent information
 */
export declare function resumeAgent(agentId: string): string
/**
 * Destroy an agent (remove from registry)
 *
 * # Arguments
 * * `agent_id` - Agent identifier
 *
 * # Returns
 * Success message
 */
export declare function destroyAgent(agentId: string): string
/**
 * Get agent information
 *
 * # Arguments
 * * `agent_id` - Agent identifier
 *
 * # Returns
 * JSON object with agent information
 */
export declare function getAgent(agentId: string): string
/**
 * Get all agents
 *
 * # Returns
 * JSON array of all agents
 */
export declare function getAllAgents(): string
/**
 * Assign a task to an agent
 *
 * # Arguments
 * * `agent_id` - Agent identifier
 * * `task_json` - JSON object containing task information
 *
 * # Returns
 * JSON object with assigned task
 */
export declare function assignTask(agentId: string, taskJson: string): string
/**
 * Complete a task
 *
 * # Arguments
 * * `agent_id` - Agent identifier
 * * `task_id` - Task identifier
 * * `result_json` - JSON object containing task result
 *
 * # Returns
 * JSON object with completed task
 */
export declare function completeTask(agentId: string, taskId: string, resultJson: string): string
/**
 * Fail a task
 *
 * # Arguments
 * * `agent_id` - Agent identifier
 * * `task_id` - Task identifier
 * * `error_message` - Error message
 *
 * # Returns
 * JSON object with failed task
 */
export declare function failTask(agentId: string, taskId: string, errorMessage: string): string
/**
 * Send a message between agents
 *
 * # Arguments
 * * `from_agent_id` - Sender agent identifier
 * * `to_agent_id` - Recipient agent identifier
 * * `content_json` - Message content as JSON
 *
 * # Returns
 * JSON object with message information
 */
export declare function sendMessage(fromAgentId: string, toAgentId: string, contentJson: string): string
/**
 * Get messages for an agent
 *
 * # Arguments
 * * `agent_id` - Agent identifier
 * * `unread_only` - If true, only return unread messages
 *
 * # Returns
 * JSON array of messages
 */
export declare function getMessages(agentId: string, unreadOnly: boolean): string
/**
 * Mark message as read
 *
 * # Arguments
 * * `agent_id` - Agent identifier
 * * `message_id` - Message identifier
 *
 * # Returns
 * Success message
 */
export declare function markMessageRead(agentId: string, messageId: string): string
/**
 * Get agent status
 *
 * # Arguments
 * * `agent_id` - Agent identifier
 *
 * # Returns
 * JSON object with agent status
 */
export declare function getAgentStatus(agentId: string): string
/**
 * Get all agent statuses
 *
 * # Returns
 * JSON array of all agent statuses
 */
export declare function getAllAgentStatuses(): string
/**
 * Reset all agents and state (for testing)
 *
 * # Returns
 * Success message
 */
export declare function resetAll(): string
/**
 * Get agent count
 *
 * # Returns
 * Number of agents in registry
 */
export declare function getAgentCount(): number
