/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Compare two temporal sequences
 *
 * # Arguments
 * * `sequence1_json` - First temporal sequence as JSON string
 * * `sequence2_json` - Second temporal sequence as JSON string
 * * `config_json` - Comparison configuration as JSON string
 *
 * # Returns
 * JSON string with comparison result
 */
export declare function compareSequences(sequence1Json: string, sequence2Json: string, configJson: string): string
/**
 * Detect repeating patterns in a temporal sequence
 *
 * # Arguments
 * * `sequence_json` - Temporal sequence as JSON string
 * * `pattern_length` - Length of pattern to detect
 *
 * # Returns
 * JSON string with pattern detection result
 */
export declare function detectPattern(sequenceJson: string, patternLength: number): string
/**
 * Analyze temporal sequence statistics
 *
 * # Arguments
 * * `sequence_json` - Temporal sequence as JSON string
 *
 * # Returns
 * JSON string with statistical analysis
 */
export declare function analyzeSequence(sequenceJson: string): string
/**
 * Normalize a temporal sequence
 *
 * # Arguments
 * * `sequence_json` - Temporal sequence as JSON string
 *
 * # Returns
 * JSON string with normalized sequence
 */
export declare function normalizeSequence(sequenceJson: string): string
/**
 * Batch compare multiple sequences
 *
 * # Arguments
 * * `sequences_json` - JSON array of temporal sequences
 * * `config_json` - Comparison configuration
 *
 * # Returns
 * JSON array with pairwise comparison results
 */
export declare function batchCompareSequences(sequencesJson: string, configJson: string): string
