/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Create a new proposal */
export declare function createProposal(id: string, title: string, description: string): any
/** Record a vote on a proposal */
export declare function vote(proposalId: string, voterId: string, voteType: string): boolean
/** Get voting results for a proposal */
export declare function getResults(proposalId: string): any
/** Close a proposal and finalize voting */
export declare function closeProposal(proposalId: string): boolean
/** Get all proposals */
export declare function getAllProposals(): any[]
