/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Initialize a new TUI Manager
 *
 * # Arguments
 * * `config_json` - JSON string containing TUI configuration
 *
 * # Returns
 * JSON string with initialized TUI info
 */
export declare function initializeTui(configJson?: string | undefined | null): string
/**
 * Render the mesh on the screen
 *
 * # Arguments
 * * `state_json` - JSON string containing screen state data
 *
 * # Returns
 * JSON string with rendered screen output
 */
export declare function renderMesh(stateJson: string): string
/**
 * Update mesh display with new nodes
 *
 * # Arguments
 * * `nodes_json` - JSON array of mesh nodes
 *
 * # Returns
 * JSON string with update result
 */
export declare function updateMeshNodes(nodesJson: string): string
/**
 * Update mesh connections
 *
 * # Arguments
 * * `connections_json` - JSON array of mesh connections
 *
 * # Returns
 * JSON string with update result
 */
export declare function updateMeshConnections(connectionsJson: string): string
/**
 * Handle keyboard events
 *
 * # Arguments
 * * `event_json` - JSON string containing event data
 *
 * # Returns
 * JSON string with event handling result
 */
export declare function handleEvent(eventJson: string): string
/**
 * Get mesh visualization data
 *
 * # Arguments
 * * `options_json` - JSON string with visualization options
 *
 * # Returns
 * JSON string with visualization data
 */
export declare function getVisualizationData(optionsJson?: string | undefined | null): string
/**
 * Display node details in panel
 *
 * # Arguments
 * * `node_id` - ID of the node to display
 *
 * # Returns
 * JSON string with node details
 */
export declare function displayNodeDetails(nodeId: string): string
/**
 * Handle zoom operations
 *
 * # Arguments
 * * `operation` - "in" or "out"
 * * `level` - Current zoom level (0.0 to 10.0)
 *
 * # Returns
 * JSON string with new zoom level
 */
export declare function handleZoom(operation: string, level: number): number
/**
 * Handle pan operations
 *
 * # Arguments
 * * `direction` - Direction of pan (up/down/left/right)
 * * `amount` - Pan amount in pixels
 *
 * # Returns
 * JSON string with pan result
 */
export declare function handlePan(direction: string, amount: number): string
/**
 * Get real-time mesh statistics
 *
 * # Returns
 * JSON string with statistics
 */
export declare function getMeshStats(): string
/**
 * Search for nodes by label or ID
 *
 * # Arguments
 * * `query` - Search query string
 *
 * # Returns
 * JSON array of matching nodes
 */
export declare function searchNodes(query: string): string
/**
 * Apply theme to TUI
 *
 * # Arguments
 * * `theme_name` - Name of the theme
 *
 * # Returns
 * JSON string with theme info
 */
export declare function applyTheme(themeName: string): string
/**
 * Export mesh state as JSON
 *
 * # Arguments
 * * `format` - Export format (json/csv)
 *
 * # Returns
 * JSON string with export data
 */
export declare function exportMeshState(format: string): string
