/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Process context data and extract key information
 *
 * # Arguments
 * * `context_json` - JSON string containing context data
 *
 * # Returns
 * JSON string with processed context
 */
export declare function processContext(contextJson: string): string
/**
 * Optimize context for better performance and reduced size
 *
 * # Arguments
 * * `context_json` - JSON string containing context data
 * * `options_json` - JSON string containing optimization options
 *
 * # Returns
 * JSON string with optimized context
 */
export declare function optimizeContext(contextJson: string, optionsJson: string): string
/**
 * Batch process multiple contexts
 *
 * # Arguments
 * * `contexts_json` - JSON array string containing multiple context objects
 *
 * # Returns
 * JSON array string with processed contexts
 */
export declare function batchProcessContexts(contextsJson: string): string
/**
 * Extract key phrases from context
 *
 * # Arguments
 * * `context_json` - JSON string containing context data
 * * `max_phrases` - Maximum number of phrases to extract
 *
 * # Returns
 * JSON array of extracted phrases
 */
export declare function extractKeyPhrases(contextJson: string, maxPhrases: number): string
/**
 * Calculate context similarity between two contexts (0.0 to 1.0)
 *
 * # Arguments
 * * `context1_json` - First context as JSON string
 * * `context2_json` - Second context as JSON string
 *
 * # Returns
 * Similarity score as a number
 */
export declare function calculateSimilarity(context1Json: string, context2Json: string): number
