/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Main scheduler struct */
export declare class MidstreamerScheduler {
  /** Create a new scheduler instance */
  constructor(configJson?: string | undefined | null)
  /**
   * Process data synchronously
   *
   * # Arguments
   * * `data_b64` - Input buffer as base64 encoded string
   *
   * # Returns
   * Processed buffer as base64 encoded string
   */
  processSync(dataB64: string): string
  /**
   * Schedule a task
   *
   * # Arguments
   * * `config_json` - Task configuration as JSON string
   *
   * # Returns
   * Task ID
   */
  scheduleTask(configJson: string): string
  /**
   * Get next task from queue
   *
   * # Returns
   * Next scheduled task as JSON string, or null if queue is empty
   */
  nextTask(): string | null
  /**
   * Get queue size
   *
   * # Returns
   * Current number of tasks in queue
   */
  queueSize(): number
  /**
   * Mark task as completed
   *
   * # Arguments
   * * `task_json` - Completed task as JSON string
   * * `output_size` - Size of task output
   *
   * # Returns
   * Execution result as JSON string
   */
  completeTask(taskJson: string, outputSize: number, executionTimeMs: number): string
  /**
   * Mark task as failed
   *
   * # Arguments
   * * `task_id` - Task ID
   * * `error_message` - Error message
   *
   * # Returns
   * Retry decision as JSON string
   */
  failTask(taskId: string, errorMessage: string): string
  /**
   * Get scheduler statistics
   *
   * # Returns
   * Statistics as JSON string
   */
  getStats(): string
  /**
   * Clear all queues and reset statistics
   *
   * # Returns
   * OK result
   */
  reset(): void
  /**
   * Process batch of tasks (simulated)
   *
   * # Arguments
   * * `count` - Number of tasks to simulate
   *
   * # Returns
   * Batch result as JSON string
   */
  processBatch(count: number): string
}
