/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Represents the KimiFannCore neural network client */
export declare class KimiFannCore {
  /** Create a new KimiFannCore instance */
  constructor(config?: object | undefined | null)
  /** Process input data */
  process(dataJson: string): string
  /** Process input data synchronously */
  processSync(dataJson: string): string
  /** Execute a neural network operation */
  execute(): string
  /** Train the neural network model */
  train(trainingDataJson: string, optionsJson?: string | undefined | null): string
  /** Make predictions on input data */
  predict(inputDataJson: string): string
  /** Close the client and release resources */
  close(): void
  /** Get client status */
  isClosed(): boolean
  /** Get configuration as JSON string */
  getConfig(): string
}
